### ISSUE TITLE
ISO hastag icon is missing in keyboard view

### ISSUE THREAD

**Issue by PastaJ36** [WootingKb/wootility-issues#1]
## Wootility Version
xx

## Firmware Version
xx
## Keyboard type
xx

## Issue description
In the Wootility when you connect an ISO keyboard the hashtag icon will not be shown on the keyboard view. Instead it will show an empty block.

## Steps to reproduce
1. Open Wootility
2. Connect any ISO keyboard

## Pictures / Video of problem
![image](https://user-images.githubusercontent.com/7443105/69052605-6b261a80-0a42-11ea-9c95-f8d0859d54ef.png)

**Comment by Rocky04** [comment]
Fixed in Wootility 3.5.2 and firmware 1.28.3.
