### ISSUE TITLE
Bug: No RGB reset after the Wootility is closed

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#10]
**Description**
You can play around with the RGB on a profile and it will be applied to the keyboard, but there is no intuitive way to reset that not permanent changes so that the stored RGB is shown again.

**Reproduction**
1. Plug in the Wooting
2. Open the Wootility
3. Change the RGB for some keys and hold on the current profile
4. Close the Wootility
5. Open the Wootility

*Now there is even a discrepance between the shown colours on the Wootility compared to the keyboard because the colour on the keyboard still shows the temporary changes but the Wootility show the stored ones.*

**Video**
https://www.youtube.com/watch?v=AWm-hM-2KSE&feature=youtu.be&t=7651

**Known worarounds**
- Replug keyboard (doesn't matter if Wootility is open or not)
- Restart Wootility and change the current profile and than switch back to the previous one
- Double press the "Mode" key while the Wootility is closed

**Possible fixes**
Reset the RGB (comand RgbColorResetAll [32]) when the Wootility is closed so the RGB override will be dropped. Maybe consider a RGB reset button for the colour settings menu.

**Desktop (please complete the following information):**
All

**Wootility and Firmware version**
All

**Keyboard Type**
All

**Comment by simon-wh** [comment]
Fixed in v3.6
