### ISSUE TITLE
Feature request: Add Mission control and Launchpad to remap for macOS 

### ISSUE THREAD

**Issue by 54wedge** [WootingKb/wootility-issues#104]
**Is your feature request related to a problem? Please describe.**
The Mission control and Launchpad keys are useful for macOS users but they are missing in the current version of wootility. It would be great if these two keys are available for remapping in wootility.

**Describe the solution you'd like**
Add these two keys to the remap function in wootility macOS version.
Bonus request: Add brightness up/down for laptop users in all version.
~~Ultimate Bonus request: Let users bind raw HID code to a key.~~ It will solve every problem I can think of, but it sounds like a lot of work to do.

**Describe alternatives or workarounds you've considered**
Remap them in system settings.

**Additional context**
Here are some links I found online. Might be useful.
- https://www.drakware.dev/blog/005-mackeys/
- https://github.com/qmk/qmk_firmware/issues/10111

### Additional information

**Platform information**
MacOS

**Wootility and Firmware version**
Wootility v4.2.2-beta
Firmware v2.2.3

**Comment by PastaJ36** [comment]
This is cool, we will add this. Didn't know it was possible to bind these for Mac.

**Comment by simon-wh** [comment]
Hi, just wanted to mention that I've been able to get this implemented and it will be available in the next significant update.

Added keys:
- Mission Control
- Launchpad
- Display Brightness Down
- Display Brightness Up

**Comment by simon-wh** [comment]
Closing this now due to the update with this included, v4.3 is close to being released in beta
