### ISSUE TITLE
RAW Analog interface only uses main layer inputs

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wootility-issues#112]
Currently, the RAW interface will only output data for a key if there is a binding on the main layer, regardless of if there is a binding on another layer that is currently being pressed.

**Comment by Rocky04** [comment]
For me this comes back to an older discussion about how the RAW interface should identify the keys.

From a technical perspective looking at it how the USB report structure is used in general these are the points how I would build the structure.

- a key has a physical travel distance with a start & end point (like 0.1 to 3.9 mm as a fixed general information)
- keys have an unique identifier (report data)
- an analog value which represents a specific key height (report data)


The question would be if only the physical keys should be send over the RAW interface or a logical representation. So for example if the interface represents only the physical keys the SDK should take account for remapping and the layering. So to use the old key codes again. This would offload complexity of the keyboard in trade off that the settings are stored on the keyboard itself. But even if the Wootings use a logical approach I think the SDK should still support the option to allow remapping and layering as additional configuration or to allow that for other future analog keyboards which may don't support that natively.

_For the physical approach the key would always send its analog value while for the logical approach only keys which are bound would do it._
