### ISSUE TITLE
DKS with FN

### ISSUE THREAD

**Issue by MegaCoolBlood** [WootingKb/wootility-issues#115]
When I set the "Fn-key" to be pressed in a DKS-Profile it sends "F".
When I set the "Fn 2-key" to be pressed in a DKS-Profile it sends "I".

Expected Behaviour:
Do not send "F" or "I" just activate the function Layer.

1. Go to D.K.S. Settings in an analog profile
2. Create a new DKS-Binding on any key
3. Add Fn or Fn 2 to the binding
4. Try the key with the Binding in a texteditor

![image](https://user-images.githubusercontent.com/37872343/139464148-0ec388b5-eaa0-401a-b49e-94d7879642c0.png)

OS: Windows 10
Wootility v4.2.2-beta
Wooting Two HE
Firmware v2.3.2

Wooting two HE, ISO German

**Comment by simon-wh** [comment]
This should be resolved with the DKS update, v4.3 which is now in beta
