### ISSUE TITLE
Toggling between keyboard profiles and inactiive profiles toggles displayed num lock state

### ISSUE THREAD

**Issue by TZer0** [WootingKb/wootility-issues#116]
**Describe the bug**
When going from on-keyboard to in-wootility profiles, the displayed num lock state (but not the actual num lock state) gets toggled. This persists until you press num lock twice or swap to an inactive profile again.

**To Reproduce**
1. Open wootility.
2. Select any profile on the keyboard
3. Click on any inactive profile
4. Repeat steps 2 and 3 over and over while observing num lock colours.

I can also confirm that it does not inherit any of the colours from the previous profile.

**Screenshots / Video**
Can provide if requested.

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Wootility and Firmware version**
Find in your Wootility Settings
Wootility v4.2.2-beta

Wooting Two HE
Firmware v2.3.2

**Keyboard Type**
Wooting Two HE, ISO UK

**Comment by simon-wh** [comment]
This should be resolved now in the latest firmware update (v2.4.5) for Wootility v4.3
