### ISSUE TITLE
Scroll lock indicator wrong after Fn unlocking

### ISSUE THREAD

**Issue by Enrice** [WootingKb/wootility-issues#118]
**Describe the bug**
The Scroll lock indicator is wrongly disabled after unlocking the Fn key, when Fn lock is mapped on the "Scroll lock" key.

**To Reproduce**
1. enable Scroll lock by pressing "Scroll lock" key
2. enable Fn lock by pressing both "Fn+Scroll lock" keys
3. disable Fn lock by pressing "Scroll lock"
4. Scroll lock indicator got disabled (not lit), but is actually enabled

**Desktop (please complete the following information):**
- Windows 10

**Wootility and Firmware version**
- Wootility v4.2.2-beta
- Firmware v2.3.2

**Keyboard Type**
Wooting 2 Lekker ISO DE

**Comment by simon-wh** [comment]
Hi, I did some digging into this today and I believe I've got this fixed up, just released firmware version v2.4.5 for Wootility v4.3 with the fix
