### ISSUE TITLE
Add Fortnite strafing angle slider similar to Wooting DM software for analog input for Wooting Two HE Lekker

### ISSUE THREAD

**Issue by gregs007** [WootingKb/wootility-issues#119]
I noticed that the fortnite strafing angle isn't adjustable in the beta Wootility when you click the "enable fortnite strafing" slider switch, and critically, when both forward and side keys are fully depressed, it does NOT result in maximum strafe possible in the game (again you can get this already using the DM software)

Requesting that there is either an angle slider specific for Fortnite where we can adjust (I currently use 100% strafe on the DM software and this angle isn't available) OR that there is a more generic menu for defining what fully depressed key combos map to on gamepads. I don't know if this issue is relevant for other games, but it might be, so having a more general approach for this could be the best thing in the long run. To be clear, all I care about in this feature request is Fortnite.

As a workaround for now I disable analog input and just use the DM software (but I'd sure love to use the analog input)

Youtube video demonstrating issue:
https://www.youtube.com/watch?v=w3pTGszPS8k

Wootility Beta 4.2.2
Wooting Two HE

**Comment by simon-wh** [comment]
In the latest beta update, v4.3, we've added support for the main angle configuration slider. We'll be doing more developments on the angle control i.e. adding single key strafing later
