### ISSUE TITLE
Issue: The user don't know if he followed the restoring procedure incorrectly

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#12]
**Describtion**
Some users don't understand that they need to put the Wooting into the restoring mode first in order to perform the restoring. Maybe because they just don't read or didn't understand it. At the moment if you click on the button for restoring without putting the keybord into the restoring mode, the Wootility will just jump to the digital default profile and because of that some users thing that the restroing was successful, which is wrong. If the user presses the restoring button when the keyboard isn't in the restoring mode, the Wootility should inform the user instead that he needs to put the Wooting into the restoring mode first and how the user can do this. By detecting which product he uses, the Wootility should just show the keys for the current product instead of all diverent ones.

**Reproduction**
1. Unplug the Wooting
2. Plug the Wooting back in (without putting it into the restoring mode)
3. Open the Wootility
4. Go to the settings menu
5. Click on start troubleshooting
6. Click on restore to ANSI or ISO depending on corerct type

**Systems**
all systems

**Wootility and Firmware version**
all versions

**Keyboard Type**
all types

**Comment by simon-wh** [comment]
I think this should be covered now by the improvements to troubleshooting made so far in Wootility v4
