### ISSUE TITLE
Key doesnt work on first use

### ISSUE THREAD

**Issue by Agrimonster** [WootingKb/wootility-issues#121]
**Describe the bug**
The first time the 0 key on the numpad is used it doesn't respond until pressed again and works afterwards. Only when the keyboard loses connection/power does this issue come back. Haven't yet experienced this on any of the other keys. Also if I save any changes to the keyboard it spams 0 until I hit backspace
**To Reproduce**
1. Power on keyboard
2. Press 0 key on numpad
3. Open text file and place cursor there
4. Open wootility and save changes to keyboard. It spams 0

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Wootility and Firmware version**
Wootility v4.2.2-beta

Wooting Two HE
Firmware v2.3.2

**Keyboard Type**
Wooting 2 HE - North America

**Comment by Rocky04** [comment]
@Agrimonster Can you reproduce the issue on the current `2.4.10` firmware?

_To me this sounds more like a calibration issue and so be specific to you than a general firmware bug._

**Comment by Agrimonster** [comment]
No, the issue seems to be resolved

**Comment by Rocky04** [comment]
@simon-wh Seems this issue can be closed...
