### ISSUE TITLE
Unable to enter BIOS or select dual-boot entries

### ISSUE THREAD

**Issue by denis-roy** [WootingKb/wootility-issues#123]
## BUG

After updating to the latest wootility & firmware, I have been unable to enter the BIOS or select dual boot entries at boot time. 

## CONTEXT

- OS: Agnostic, happens before booting to OS
- Wooting Two HE ANSI US but seems to affect Lekker users as well
- The keyboard lighting is on, so there is power going to the board. 
- It doesn't seem to matter if the keyboard is plugged directly or through a hub. 
- The keyboard works as expected after the OS is booted.

## WORKAROUND *

As reported by Ted in the `#helpdesk_for_keyboards` Discord channel on 2021-12-11 @ 8.23am ([Discord Link](https://discord.com/channels/167181566978555904/337667773943775233/919217802651525130)):

- Toggling `NKRO Disable` to the _**ON**_ position in the `wootility -> Settings -> Keyboard Settings` can be used as a workaround.

## TO REPRODUCE

1. Update to wootility v4.3.4-beta
2. Update keyboard to firmware v2.4.5
3. Reboot
4. Try to enter bios with DEL or F2 key

**Comment by drteaspoon420** [comment]
W2LE ISO

**Comment by snailrag** [comment]
I have the same issue with W2 HE ISO
The keyboard also doesn't work in grub boot menu
Fast boot is not enabled, tachyon mode is off.
Disabling NKRO seems to fix it, but also means the keyboard frequently puts double or triple characters when shift is pressed.

**Comment by simon-wh** [comment]
Thanks everyone for the reports and info, I've got a fix in development that has resolved this issue in my testing. Hopefully will be pushing a firmware update out later today 👍 

> Disabling NKRO seems to fix it, but also means the keyboard frequently puts double or triple characters when shift is pressed.

btw, I've got a fix in for this as well 😄

**Comment by simon-wh** [comment]
The firmware update with the fix, v2.4.6, is now out for Wootility v4.3
