### ISSUE TITLE
Issue: The user don't know in which Xbox slot the Wooting is in

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#13]
**Describtion**
There is no good way to show the user in which Xbox slot the Wooting is currently in. Nearly all games only accept the input from the Xbox controller in slot 1. Because of this the Wootility should show the current slot number of the Wooting somethere.

**Reproduction**
1. Unplug the Wooting
2. Reboot the system
3. Connect another Xbox controller
4. Connect the Wooting
5. Now the Wooting should be in slot 2 and you don't know why the games don't accept the input from the Xbox controller of the Wooting

**Systems**
all systems

**Wootility and Firmware version**
all versions

**Keyboard Type**
all types

**Comment by simon-wh** [comment]
Availble in v3.6
