### ISSUE TITLE
Don't ignore System Keyboard Layout.

### ISSUE THREAD

**Issue by 0xMiya** [WootingKb/wootility-issues#130]
**Problem Description**
The Wooting 2 HE ignores the OS keyboard layout. It's possible to remap keys using the Wootility, but this only works as long as the same symbols (punctuation marks, numbers, etc.) are on the same key. For example, it's easy to remap to the Dvorak layout, since Dvorak only changes the position of keys. Using the _Programmer_ Dvorak layout on the other hand is not possible, since punctuation marks, numbers and other symbols are on completely different keys. (All numbers are on shift, '1' and '(' are on the same key, instead of '1' and '!').

**Steps to Reproduce**
1. Connect Wooting 2 HE to computer.
2. Start typing.
3. OS keyboard layout is ignored.
4. Try to remap keys using Wootility (Version 4-3-5-beta).
5. Wootility only allows to remap "whole" keys, keyboard layouts like Programmer Dvorak cannot be produced.

**Desktop**
 - OS: Arch Linux (5.15.11-arch2-1)

**Wootility and Firmware version**
Wootility v4.3.5-beta
Wooting Two HE Firmware v2.4.6

**Keyboard Type**
Wooting Two HE + ANSI - United states

**Comment by simon-wh** [comment]
The keyboard does not ignore the OS layout, the OS is the one that determines what text character should be input based on the keycodes that are sent from the keyboard.

In the example you gave with holding shift, all the keyboard does is tell the OS that the shift key and e.g. 1 are pressed. It is the OS that interprets what should be input when you press 1 with shift held.

To achieve what you desire you will need to configure your OS layout to be programmer dvorak and leaving your keyboard as QWERTY (as OS layouts generally will assume it's converting from a QWERTY layout as that is normally hardcoded on a keyboard)




As an aside, when it comes to different keyboard languages the keyboard is always telling the OS the exact same thing, the only difference being that the user has set their language in the OS so it inputs the appropriate characters

**Comment by 0xMiya** [comment]
What you wrote is exactly what I expected to happen, but for some reason didn't. I tested it out again and the problem seems to be the following:

1. Set OS keyboard layout to Programmer Dvorak (`setxkbmap us dvp`).
2. Connect Wooting Two to computer.
3. In the Wootility app under "Remap" select the default (qwerty).
4. Type something: the keyboard will type using qwerty. (Which is wrong, it should be Programmer Dvorak.)
5. Set the layout so something else (`setxkbmap dvorak`)
6. Type more: It's correctly using Dvorak now.
5. Set the layout to Programmer Dvorak again (`setxkbmap us dvp`)
6. Type some more: the keyboard now correctly types using programmer dvorak.

**Fix:** After connecting the keyboard to the computer, the layout needs to be set _again_.

**Comment by 0xMiya** [comment]
I've tested it now with other keyboards and had the same problem. Seems to be something with X11 maybe, unrelated to the Wooting keyboard.
