### ISSUE TITLE
[Wootility] FN layer with a different colour profile while it's active

### ISSUE THREAD

**Issue by susscribe** [WootingKb/wootility-issues#131]
**Description:**
it would be extremely helpful to both have visual feedback the FN layer is active, as well as the ability to define a new colour scheme that highlights points of interest.
would facilitate using the fn layer bindings as well. while still not a fully fledged legend in the caps, it would show where things are and have a the possibility of a colour cod for the key-output the user can define for themselves (example, white for characters, yellow for the xbox Y button, red for modifier keys, green for special characters, blue for OS related binds, etc).

**Solution proposal:**
just like each profile has a colour scheme, let us assign one as well to each layer, the UI seems to have space for it too without issue.

**Comment by Rocky04** [comment]
Maybe by adding the layer selection of the remapping for the color selection so they share the same selection. Meaning both show only the "Fn Layer 2" is this is present.

![image](https://user-images.githubusercontent.com/5910569/147703411-082013a3-f24f-471d-978a-ca8bc8eb4dd4.png)

**Comment by DarrenVs** [comment]
If memory is a concern, playing with the brightness could achieve some similar result.

In this idea any key without a Fn binding would dim down 50% to indicate what keys are bound while you're holding down the Fn key.

**Comment by piperdeck** [comment]
came here to say that I want this as well.

**Comment by piperdeck** [comment]
Any movement on this feature?

**Comment by simon-wh** [comment]
> Any movement on this feature?

I've got an initial implementation for this feature working and I'm aiming to have it included in the next update. It will only be supported on Lekker switch based boards (so I don't get Flaretech users hopes up, as those boards don't have enough onboard memory for it sadly)
