### ISSUE TITLE
Feature Request: simple macros please to get chars like ```{```

### ISSUE THREAD

**Issue by michaelkarrer81** [WootingKb/wootility-issues#134]
I use the wooting keyboard mainly for programming. The main problem with programming and a German keyboard layout are (in my opinion) the bracket keys ```{```, ```}```, ```[```, ```]```,```(```, ```)``` and alike because they are relatively bad located. 

Therefore it would be fantastic to map all the the brackets and needed chars simply to```Fn``` + ```regular reachable key```  like ```Fn``` + ```j```, ```Fn``` + ```k```, ```Fn``` + ```l``` and so on.

**EXAMPLE:** Use the keys ```Fn``` + ```f```  to trigger the macro ```SHIFT``` + ```8([``` to create the character **```(```**

**Keyboard Type**
All :) but mine are: Wooting Two HE ISO DE, Wooting One ISO DE

**Comment by Rocky04** [comment]
You want macro support which will take a while until this would be implemented or DKS support per layer. I assume the later is more likely to be implemented sooner while it would be limited to the analog profiles.

**Comment by michaelkarrer81** [comment]
Yes, DKS per layer would already solve my request. :) 

So hopefully this feature may arrive soon. If needed i will happily jump in as a beta tester ;)

**Comment by simon-wh** [comment]
> Yes, DKS per layer would already solve my request. :)
> 
> So hopefully this feature may arrive soon. If needed i will happily jump in as a beta tester ;)

Btw, if you haven't already seen, DKS per layer is now possible since Wootility v4.4 which was released for the 60HE. If you're still on Wootility v4.3 you may need to install the stable channel to get v4.4 (we have a settings transfer from beta -> stable but I'm not able to get a windows release for that this week)
