### ISSUE TITLE
Linux AppImage Desktop Entry category is wrong

### ISSUE THREAD

**Issue by Micha-ohne-el** [WootingKb/wootility-issues#137]
**Describe the bug**
The Linux AppImage's Desktop Entry contains the line `Categories=development;`. But that doesn't work, as the category name must be capitalized (`Development`). Currently that causes the app to show up as uncategorized, which means it may or may not show up at all in a global menu.
I suggest that it gets changed to `Categories=Utility;`, which would make a lot more sense in my opinion. That is really the best category for this type of application.

**To Reproduce**
1. Download the latest Wootility Lekker Linux AppImage (v4.3.5-beta)
2. Make it executable with `chmod +x wootility-lekker-beta-4.3.5-beta.AppImage`
3. Run `./wootility-lekker-beta-4.3.5-beta.AppImage --appimage-extract wootility-lekker-beta.desktop`
4. The desktop file gets extracted to `./squashfs-root/wootility-lekker-beta.desktop`.

**Desktop**
OS: Manjaro Linux (KDE)
Note that this is Distro-independent.

**Wootility and Firmware version**
4.3.5-beta.

**Keyboard Type**
Wooting two HE.
Note that this is Keyboard-independent.

Lastly I just want to say thank you for even providing a Linux build. It was one of the most compelling reasons for me to buy a Wooting keyboard and I appreciate it a lot <3

**Comment by simon-wh** [comment]
Good catch, I'll look into sneaking this small fix into the next v4.3 slated for this week
