### ISSUE TITLE
Rapid Trigger settings per key

### ISSUE THREAD

**Issue by 0nlyDev** [WootingKb/wootility-issues#139]
Rapid trigger is awesome, but having it only as a global setting can be a disadvantage in games. For example when I use low actuation point and rapid trigger in WoW, I sometimes accidentally stop movement because I ever so slightly moved my finger away from WASD (this actually killed me today in a dungeon) - in FPS games this is the wanted behavior,  but not really in games like WoW for example.

**Describe the solution you'd like**
Need to have the option to set rapid trigger settings per key.

**Describe alternatives or workarounds you've considered**
There isn't, only option I have is to increase the rapid trigger cut off for all keys to avoid accidental deaths (but this sacrifice the other keys responsiveness that rapid trigger provides - it probably will be best if i actually turn off the rapid trigger and then I'll have to increase the activation point to compensate :( )

**Keyboard Type**
Wooting Two HE

**Comment by 0nlyDev** [comment]
Maybe for starters just add a feature to disable rapid trigger on per key basis if the fully customizable feature is too hard/complex to implement.

**Comment by DarrenVs** [comment]
Rapid Trigger can now be configured `on` or `off` per key.

**Comment by Saffsanity** [comment]
Since we can set the actuation point of rapid trigger globally, is there any way to set the actuation point for rapid trigger on a per-key basis?

**Comment by BigBrainAFK** [comment]
> Since we can set the actuation point of rapid trigger globally, is there any way to set the actuation point for rapid trigger on a per-key basis?
> 
> @DarrenVs @simon-wh

you mean the sensitivity?

**Comment by Saffsanity** [comment]
@BigBrainAFK yes the sensitivity, how far the key has to be unpressed to stop its activation

i.e. WASD immediately stop pressing upon keylift, while other keys stop travel at 0.5mm
