### ISSUE TITLE
Fn key is not being recognised? SCnnn?

### ISSUE THREAD

**Issue by CaipaRinha** [WootingKb/wootility-issues#141]
Or I still dont know how to properly use it.

I wanted to change switch my AutoHotkey (ahk) combos to the Fn key today. Turns out i cant get AHK to listen to my Fn key, irrespective of if wootility is running in the background or not. (whether under classic controller or xbox), also now tested with newest firmware and software update.

The Fn key seems to suppress every other key and sends nothing to to the system. Strangely enough I can get the SCnnn code for Fn+Home (Volume Down, 12E a)

Please, please allow us to bind additional keys to Fn combos (or, since I think this is not possible,) maybe bind SCnnn codes to the combos which we can then use for nefarious uses in AHK? It works with volume up and down, but we (I) need more buttons.

I have an Fn layer but no real use for it, as I have no option to bind more keys to it.

Yes I know this is similar to already mentioned topics.

**Comment by simon-wh** [comment]
The Fn key gives you access to an additional 'Remap' layer which has different bindings per key, e.g. 
![image](https://user-images.githubusercontent.com/10797576/154996423-c2d698e8-6d08-4be5-b4bc-a8b0f8615c9f.png)
 
For your use, I'd recommend making use of the F13 - F24 keys as they are generally unused and can be bound to keys on the Fn Layer to be picked up by your AHK script
