### ISSUE TITLE
Provide key label or at least tooltip to distinguish keys

### ISSUE THREAD

**Issue by Enrice** [WootingKb/wootility-issues#146]
**Describe the bug**
On the remapping page some numpad keys cannot be distinguished from their non-numpad counterparts by their label.
Examples: / * - + , Enter
Only the numbers are named differently (Num...) - so that's ok.

**Wootility and Firmware version**
v4.3.10-beta
v2.4.10

**Keyboard Type**
Wooting 2 lekker edition

**Comment by simon-wh** [comment]
Good catch, very important one to get in

**Comment by simon-wh** [comment]
Do you think just the addition of tooltips would be adequate or would it be helpful to also have the display label include "Num"?

**Comment by Enrice** [comment]
I can only tell the following: keep it consistent.
On the one hand the labels should not be too long to nicely fit in minimum window size or at least not look too awkward. On the other hand with tooltip only it is obviously not possible to distinguish without hovering.

I would probably think about a smaller font? Then the label text can easily be larger.

**Comment by simon-wh** [comment]
Thanks for the feedback, the issue was auto closed due to the code changes to fix this being merged. It'll be included in the next update

**Comment by DarrenVs** [comment]
I would love to see ISO backslash `\|` key labeled too so it can be distinguish from regular backslash `\|`
![image](https://user-images.githubusercontent.com/2780639/157472536-ad139bbe-ca47-4b24-b11b-5d9eb4b9e4af.png)
> US keyboard layout (and a hand full of others)

**Comment by Enrice** [comment]
Do they really send different scan codes? Or, is there a layout that has BOTH keys?

**Comment by neube3** [comment]
I would consider this (and #213) not fixed. Both light and dark themes are affected.

Longer comment and notes in #213.
