### ISSUE TITLE
Right-click on indicator color circle retrieves primary color instead of indicator color

### ISSUE THREAD

**Issue by mikey-dg** [WootingKb/wootility-issues#147]
**Describe the bug**
In the Colour tab of the Wootility, right-clicking on an indicator color circle retrieves the primary key color instead of the indicator color.

More specifically, holding the right mouse button down does retrieve the indicator color, but releasing it while still over the indicator circle will then retrieve the primary key color.  This seems to be because primary key color retrieval is normally handled on button release (which can be demonstrated by right-clicking a key of one color, noting that no color is retrieved, then moving to a key with a different color and releasing), but the indicator click handling performs it on press, and the release event is being passed to the main key object.

**Workaround**
It is possible to retrieve the indicator color of a key by clicking and holding the right mouse button on the indicator circle and then moving the cursor outside the keyboard map before releasing.

**To Reproduce**
1. Go to the Colour tab of the Wootility
2. Click and hold the right mouse button on an indicator circle of a different color than the primary key color
3. Observe that the indicator color is retrieved while the key is held
4. Release the right mouse button while still over the indicator circle
5. Observe that the key's primary color is then retrieved

**Desktop:**
OS: Windows 7

**Wootility version**
Wootility v.4.3.10

**Comment by simon-wh** [comment]
Good catch, I'm able to replicate this, looking into a fix now

**Comment by simon-wh** [comment]
Got a fix queued up to be included in the next Wootility update 👍
