### ISSUE TITLE
Snappy Joystick behaves inconsistent  

### ISSUE THREAD

**Issue by ahobowithashotgun** [WootingKb/wootility-issues#149]
**Describe the bug**
 set up an analog profile  where WASD is bound to the according directional input for left thumbstick.  set the "snappy joystick" in advanced settings and the "square joystick output" . Now when  fully press D for right movement , hold it down and then fully press A for left movement the joystick "snaps" to full left movement immediately , however when you do this vice versa (holding down A and the pressing D ) the joystick doesn´t  snap to full right movement , but stays put on full left until you let go a bit from A and only then snaps over to full right .
same goes for  W and S  where  W behaves like  D and S behaves like A as described above
(the "square input mode" doesn´t seem to have an effect on the described issue , i simply included it because i got aware of this Bug while it was enabled , the described behaviour is the same under the "default" circular input settings )

the  first described behaviour should be  consistent on all keys .. when i hold down a key and then press the key for the opposite directional input it should snap to that without having to let go of the first pressed key.

**To Reproduce**
1. Go to 'gamepad response ' in the browser version of wootility (wootility.io)
2. Click on any analoge profile  
3. Click on 'advanced settings'
4. enable "Snappy joystick"
5. assign WASD to the according directional inputs for the left thumbstick in  "Gamepad Mappings"
6. hold down D then press and hold down A wile keeping D fully pressed
7. observe the indicator on the Gamepad tester "snap" from full right movement to full left movement as soon as you have fully pressed the A key 
8. hold down A then press and hold down D wile keeping A fully pressed
9. observe the indicator on the Gamepad tester  now stay put on full left movement until you let go of the A key then the indicator "snaps" to full right movement 
10. repeat the procedure with W and S keys where W will behave like D and S will behave like A
11. ERROR : all keys should behave the same .. ideally. in this case like the Keys D and W are described ,meaning the joystick should snap to the opposite  directional input when this  is fully pressed even if the other directional input is fully pressed already 

**Screenshots / Video**

**Desktop (please complete the following information):**

 - OS: Windows 10

**Wootility and Firmware version** : 

Wootility v4.3.11 (the browser version)

**Keyboard Type** : 

Wooting two HE

**Comment by DarrenVs** [comment]
This topic was also discussed in the Discord, more on that here:
`discord:///channels/167181566978555904/337667773943775233/962114789667110983`

---
We are aware of this favouritism in the axes on snappy joystick setting, and it would likely be changed in the next update containing analog changes.

However, there is still the question on what the best/most-wanted result is from pressing two keys for the same amount.
I can see two ways to resolve this:
1) They cancel each other out (behaviour of non-snappy)
2) The last most-pressed key gets priority

**Comment by CaptainBoggle** [comment]
I think option 2 would be the preferred way to handle this in almost all games, and the results of the poll on discord seem to agree.

**Comment by simon-wh** [comment]
Hey, just wanted to share that the initial patch for this is available in the latest Stable Wootility release (v4.5.0). For now, we just have the 2nd behaviour mentioned above to help this (for reference):
> The last most-pressed key gets priority

We are considering adding more settings to this in the future to allow more control over the behaviour when both keys are active. If you have any requests for this, feel free to share it here :)
