### ISSUE TITLE
Wootility: Some key images are poorly-rendered when rescaled

### ISSUE THREAD

**Issue by mikey-dg** [WootingKb/wootility-issues#150]
**Describe the bug**
In all tabs of the Wootility, some key images lose significant details due to poor rescaling when mapped to a standard-size key.  For example, when the Calculator button is mapped to any standard-size key, the default Wootility window size renders it as an empty square:
![calc-default](https://user-images.githubusercontent.com/96163084/163692679-09a8ca64-e71c-41f4-8717-8cd9fdce7e08.png)

As the Wootility window is resized and the key images are rescaled, sometimes missing parts of the image will momentarily appear:
![calc-mid](https://user-images.githubusercontent.com/96163084/163692204-da652ba7-959e-4569-a57d-832899bcd07e.png)
The amount of detail shown depends on which key it's mapped to - this is the maximum amount of detail shown at any window size up to 1080p when mapped to the Mode key, but some other keys of the same size will inexplicably rescale it differently, showing more (but rarely all) details.

This problem is not present at any window size when mapping Calculator to a Ctrl-sized key or larger:
![calc-ctrl](https://user-images.githubusercontent.com/96163084/163692405-bf9bf6af-7ce4-4564-a26c-7bbfd67a0f70.png)

Many other key images with single-pixel lines or dots are poorly-rendered on a standard key at various Wootility window sizes, but only the MacOS Launchpad and Calculator keys seem to lose details entirely.  Nearly all of the system/OS shortcut keys and Increase/Decrease Keyboard Brightness look poor at the default Wootility size and have blurry or fluctuating lines when the window is resized.

**To Reproduce**
1. Open the Wootility, leave at the default window size
2. Map Calculator to any standard-sized key, noting that it is shown as an empty square
3. Optionally, resize the Wootility window and note various image details appearing and disappearing as the window is resized
4. Optionally repeat with other keys that render poorly at standard key size

**Desktop Settings**
1920x1080, 96 DPI (default)

**Wootility version**
v.4.3.11-beta

**Comment by simon-wh** [comment]
I suspect that this shouldn't be an issue anymore as I converted all the icons to use pure SVGs a while back
