### ISSUE TITLE
Fortnite Dropping To 8-11 FPS When Using Wooting Double Movement Software With Wooting 60HE.

### ISSUE THREAD

**Issue by Thriftty** [WootingKb/wootility-issues#163]
Whenever I attempt to use this keyboard for double movement on Fortnite, the game drops to 8-11 FPS when I try to move. It is recommended on the wootility-lekker app to use the double movement software and I followed each step closely, yet the issue persists. The problem is not my computer's hardware either, I have a Ryzen 7 5800x, 3080ti, 32 GB of ram, 750w psu, etc. The frame drops don't happen in other games either, I tested it on games that are less trying on my computer like among us and there was no issue. I will try it with higher, more demanding games, but I doubt they will join Fortnite in dropping to 8-11 FPS. I have used wooting double movement software before with other keyboards and have had no problem, and the keyboard itself without the double movement software has zero problems, however, when paired with the software, the game all but crashes.

Steps to mirror the behavior:
1. Go to Wooting Double Movement software (most recent version) and find your way to "360 Movement" in the Advanced Mode tab, with your Wooting 60HE connected.
2. Click "Enable 360 movement from Wooting kb" to activate the double movement, make sure the double movement is enabled by clicking above as well, or press 'ctrl'+'p'
3. Check to see if the keyboard and movement are working via the 360 movement tester in the 360 movement tab.
4. If working, open Fortnite.
5.  You can try it out in the lobby by just holding one of your movement keys, but it is much easier to see in a match.
6. Enter a match (Creative recommended) and move around.
7. Frames will drop to 8-11 FPS when holding a movement button.

-Side note, for the Wooting 60HE settings I am using: Analog Profile 3 on the Wooting 60HE with rapid trigger (full) enabled, continuous rapid trigger enabled, sensitivity to 0.1mm, Tachyon mode enabled, actuation point on 0.1mm on all keys, Remap keys (linked) enabled, no advanced keys, Xbox Controller Mapping, Enable keyboards keys enabled, Gamepad mapping override disabled (had it enabled before and the problem still occurred), linear analog curve, and Enable angle adjustment enabled and at 60 degrees (this is where the "Fortnite?" tab is and where it recommends the double movement software). 

OS/USB: Windows 10 with no USB port issues.

Version of software: most recent version of wooting double movement software and wootility-lekker as of June 23rd, 2022.

Keyboard: Wooting 60HE

**Comment by simon-wh** [comment]
Make sure you don't have any gamepad mappings on the on-board keyboard profile you're using with Fortnite. If you have both the keyboard and the DM app doing gamepad inputs it is a likely cause for this issue. If that doesn't work you could also share your profile code so we can try and determine the cause

**Comment by Thriftty** [comment]
That was the problem, thank you so much I have no idea why I didn't try that.
