### ISSUE TITLE
key lock led turnoff does not reset on switching profiles

### ISSUE THREAD

**Issue by botn365** [WootingKb/wootility-issues#167]
**Describe the bug**
if you have a key locked the led turns off but when you switch profile the key gets unlocked but the led is still turned off
led only turns back on if i re lock the key and unlock it

**To Reproduce**
lock key
switch profile
led remains off

**Desktop (please complete the following information):**
 - OS: linux

**Wootility and Firmware version**
v4.4.9
v2.5.10

**Keyboard Type**
two he

**Comment by simon-wh** [comment]
Thanks for the report, I'll take a look at this start of next week, should be a quick fix :)

**Comment by simon-wh** [comment]
I've implemented a fix for this that will be included in the next update :)
