### ISSUE TITLE
Feature Request: Energy saving modes

### ISSUE THREAD

**Issue by costis-t** [WootingKb/wootility-issues#171]
Problem: Electricity rates have skyrocketed.

Solution so far: Turning off the LEDs (from high) saves about 2 Watt per hour. This translates to about 14 Euro per year having the LEDs turned on 24/7 (with a rate of 0.8Euro/kWh). 
Further, I use [uhubctl](https://github.com/mvp/uhubctl) to turn off the keyboard when system idles, but I haven't measured the consumption differences, yet, nor is it very stable.

I wonder if there is place in the wootility user interface to take other actions that could lower the consumption even further like perhaps:
- implementing an energy saving mode (e.g. sleeping after X minutes of inactivity and waking up by pressing Esc)
- disabling  the numpad, arrow keys, function keys, etc... 
- making the response of the keyboard slower, but sufficient for office use.

Think marketing: when the prices go even higher, the keyboard will pay (partially) itself... (!) :D

**Comment by PastaJ36** [comment]
I like this calculation. We already have a function to automatically dim the LED after some time of inactivity, that should drop the bill by a lot. You can find it in the Keyboard Settings:
![image](https://user-images.githubusercontent.com/7443105/189607533-321c18fa-f863-48bd-8083-7557bc1b6f1d.png)
