### ISSUE TITLE
Allow binding of mod-keys on Fn-Layer

### ISSUE THREAD

**Issue by shawly** [WootingKb/wootility-issues#175]
**Is your feature request related to a problem? Please describe.**
Wootility allows me to bind stuff like F13-F24 on the Fn layer, but it would be even better if I could include mod-keys in these bindings.

**Describe the solution you'd like**
I'd like to add mod-key bindings + the actual key. For example bind `Win L` + `F13` to `F1` on the `Fn` layer, so I can press `Fn` + `F1` to get my shortcut instead of having to map `Win L` on the function layer and press `Fn` + `Win L` + `F1` to use the shortcut.

**Describe alternatives or workarounds you've considered**
Binding mod keys like `Win L`  on the function layer so I can press `Fn` + `Mod-Key` + `Desired Key` works but is just tedious because more complex combinations with multiple mod-keys force me to bend my fingers. Stuff like `Fn` + `Win L` + `Alt R` + `Shift R` + `F1` is kind of like gymnastics for my hands. While on my GH60 with QMK I can just bind this combo on a single key.

**Additional context**
The QMK firmware for example supports this.

**Wootility and Firmware version**
Wootility v3

**Keyboard Type**
Wooting One ANSI

**Comment by simon-wh** [comment]
Hey @shawly,

If I understand your request properly, I believe this is possible in Wootility v4. In v4, we have 'Advanced keys' which is an evolution of DKS (so there can be multiple types of these advanced bindings) and it allows you to bind them on Fn layers. As a result, you would be able to achieve this by making a DKS binding on the fn layer with those bindings.

e.g.
![image](https://user-images.githubusercontent.com/10797576/205295301-cb921fd7-2d3b-4a50-a1b3-c2b7d72ba4e6.png)

The support for the Wooting One & Two in Wootility v4 is currently in Alpha, so if you ping me or one of the team on Discord we can add you to it if you want to try it out now :)

**Comment by shawly** [comment]
This is exactly what I'm looking for! If you have an AppImage for the v4 alpha I'd be stoked to try it out!

**Comment by shawly** [comment]
As it seems, DKS isn't available on digital profiles (yet?). Is support for that planned for the future?

**Comment by BigBrainAFK** [comment]
DKS is available on digital

**Comment by shawly** [comment]
![image](https://user-images.githubusercontent.com/6448794/205498759-1c305d1e-ad13-42cd-aaba-4f21d507920a.png)

Well, it isn't in the v4 alpha at least. Even if I create an inactive profile with DKS and set it as digital profile, the DKS keys get disabled.

**Comment by simon-wh** [comment]
@shawly Yeah, it's all a bit of a memory limitation. The Lekker-based boards have a flash chip so aren't memory limited for profile configuration like the flaretech boards are. Lekker boards are able to have Advanced keys on the digital profile as well. For the flaretech boards, you may remember that in v3, it was limited to 20 *total* DKS bindings, whereas with v4, I was able to optimise the memory layout to give 20 advanced key slots to each analog profile, giving 60 total. This is kinda the upper boundary of what's possible with the limited memory on Flaretech, so it's unlikely to change, unless some trickery is done, I'm already pushing the limits of what the Flaretech boards are capable of
