### ISSUE TITLE
Keyboard don't wake up properly = Not working RGB, CapsLock and Shift keys

### ISSUE THREAD

**Issue by yeradis** [WootingKb/wootility-issues#18]
**Describe the bug**

After wake up the keyboard does not show RGB lightning also CapsLock and Shift key does not work making it impossible to enter capitalised text needed for the password 

**To Reproduce**
- put the laptop to sleep
- after some minutes the keyboard went to sleep too, cause stoped showing any RGB ,any light anything
- after some more minutes started touching any keys at the keyboard, the external display turned on
- keyboard doesn't show any lighting at all
- characters appear at the input field (havent tried them all)
- shift key and capslock key does not work at all, i was not able to enter my password that has capitalised characters
- then i remove the keyboard from the usb and reconnected, the keyboard RGB lights appeared
- capslock and shift key started to work cause i was able to enter my password, the input filed showed the icon saying capslock is activated, this was not appearing before re-replug when the

**Video**

[no lights and caps or shift not working IMG_8330 480p.mp4.zip](https://github.com/WootingKb/wootility-issues/files/4318034/no.lights.and.caps.or.shift.not.working.IMG_8330.480p.mp4.zip)

**Desktop (please complete the following information):**
 - OS: MacOs Catalina v10.15.3
 - MacBook Pro (Retina, 15-inch, Mid 2015)

**Wootility and Firmware version**
 firmware version: 1.27.3
 Wootility version: 3.4.5

**Keyboard Type**
Wooting one  + US ANSI

**Comment by yeradis** [comment]
User `Chronocide Comando` said at discord:

In my case (desktop PC with Windows 10) the issue with keyboard not waking up properly only occurs when PC is woken up by pressing a key on Wooting keyboard. If I use the power button or another keyboard, Wooting wakes up just fine.

**Comment by yeradis** [comment]
Tried what `Chronocide Comando` mentioned, used another keyboard and even the mouse and the Wooting wakes up without issue

**Comment by yeradis** [comment]
Looking for some info regarding Macs they recommend doing a SMC reset, but didnt work https://support.apple.com/en-us/HT201295 i'm observing the same behaviour

**Comment by yeradis** [comment]
Did a test on a Windows Laptop

- put the windows to sleep
- keyboard stop showing any lights same for the laptop
- touched the keyboard and start showing some lighs
- needed to touch the keyboard again for the laptop screen to show something

is this the correct behaviour? see attached video
[wake up pc.mp4.zip](https://github.com/WootingKb/wootility-issues/files/4324869/wake.up.pc.mp4.zip)

**Comment by Rocky04** [comment]
I think yes...

**Comment by PastaJ36** [comment]
> User `Chronocide Comando` said at discord:
> 
> In my case (desktop PC with Windows 10) the issue with keyboard not waking up properly only occurs when PC is woken up by pressing a key on Wooting keyboard. If I use the power button or another keyboard, Wooting wakes up just fine.

We're still not a 100% sure why this happens. What should happen is that the PC sends a USB command to the keyboard that it can wake up. This should happen even if the keyboard is the one that awakens the PC, like it does in your Windows Laptop example. 

Maybe there is something Mac specific (or in general) we're missing in the sleep keyboard logic. Another option is to have some sort of key combination that forces your keyboard to wake up.
