### ISSUE TITLE
Add support for OpenRGB, through the implementation of its SDK

### ISSUE THREAD

**Issue by dbfhvsfvdg** [WootingKb/wootility-issues#183]
**Is your feature request related to a problem? Please describe.**
Control of RGB functionality is too limited.

**Describe the solution you'd like**
Add support for OpenRGB, through the implementation of its SDK.
The Wootility already has support for "Razer Connect", and OpenRGB is an open source alternative, capable of doing the same thing, but for hundreds more devices across most major pc peripheral manufacturers.

**Comment by simon-wh** [comment]
OpenRGB already supports our keyboards, although, it appears it may be missing support for 60HE ARM currently

**Comment by dbfhvsfvdg** [comment]
Please re-open this, as my request has been misunderstood, so the "solution" is wrong and irrelevant.

**Comment by BigBrainAFK** [comment]
I mean you could just use Artemis then can't you?
