### ISSUE TITLE
Exchanging active profiles overwrites Remaps

### ISSUE THREAD

**Issue by wunditta** [WootingKb/wootility-issues#190]
When you unlink the remap keys and make changes (e.g. removing a key to assign a gamepad mapping) and this is an active profile, exchanging this by an inactive profile, overwrites the remaps of the former inactive one. When exchanging profiles everything is a mess in no time.
In more detail:
* You have profile A as active and keys ESDF are removed (empty). Remap keys are unlinked.
* You have profile B as inactive and keys ESDF are not removed. Remap keys are unlinked.
* You drag & drop profile B over A so that both are exchanged.
* Then now active profile B has ESDF removed, well as profile A (still removed).
* There is no way to get the correct remapping back, as by exchanging profiles UNDO is not available anymore. Replacing B with A again changes nothing, as still both profiles will have ESDF removed.

To make it short: this drives me crazy and it is impossible to keep the profiles correct if you have to exchange them often (as more and more games need there own profile, or I want it do recolor depending on game, etc)

Please FIX THIS ASAP!!!!

**Comment by simon-wh** [comment]
I believe this issue should be fixed in the latest stable release (v4.5.0)
