### ISSUE TITLE
DKS events triggers inconsistently

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#2]
# Wootility Version
3.3.3

# Firmware Version
1.27.1

# Keyboard type
Wooting One

# Issue description
When multiple DKS events are on the same column, it is inconsistent in which order the events will trigger.

# Steps to reproduce
1. Open Wootility
2. Create a Analog profile with a DKS binding similar to the one below
![image](https://user-images.githubusercontent.com/2780639/69053036-cd622980-0a08-11ea-91af-dadce996e4d3.png)
3. Open Notepad and start pressing the key in successions
4. Notice the results differing from previous keystrokes

# Pictures / Video of problem
[![Click for video format](https://user-images.githubusercontent.com/2780639/69054449-def90080-0a0b-11ea-97b2-8bcf1b4d1966.gif)](https://i.imgur.com/J64FnUC.mp4)
**Results:**
> 312
> 123
> 123
> 123
> 312
> 312
> 312
> 123
> 312
> 312
> 312

**Comment by Rocky04** [comment]
This happens by design because of how nKRO works. Improving that nearly mean to implement macro support, so it's not easy to implement.

So to correct that behaviour each row needs to be delayed at least one cycle compared to the row above, but only for key downs (because otherwise key ups can lead to problems).

**Comment by PastaJ36** [comment]
What Rocky said here is correct, would be hard to solve. I'm going to close. If you have a real life scenario where this impacts please re-open.

**Comment by Rocky04** [comment]
**To be clear, in theory there is an easy solution for this but the implementation isn't that easy.**

If the output of the seconds line is always 1 ms delayed compared to the first one and so the third to the second and so on, the problem is solved.
