### ISSUE TITLE
Wootility App Icon color is not the best choice when over a light background

### ISSUE THREAD

**Issue by yeradis** [WootingKb/wootility-issues#20]
**Describe the bug**
The icons is not visible or almost not visible in some scenarios like having a white background

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/666944/76417823-db63fd80-639d-11ea-8ac1-8eed6428f06c.png)
![image](https://user-images.githubusercontent.com/666944/76417839-e159de80-639d-11ea-9f37-e0e4b169795b.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Wootility and Firmware version**
Wootility is version: 3.4.5

**Comment by PastaJ36** [comment]
Thanks for the feedback. I think we'll add an outline or something so it can work in all backgrounds

**Comment by PastaJ36** [comment]
Resolved in >v3.5.2
