### ISSUE TITLE
Race condition if the numlock and caps lock indication is changed together

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#21]
**Describtion**
Like the old bug on the W1 the caps lock indication on a W2 sometimes show a wrong colour when the caps lock and the num lock key is pressed repeatedly together. If the system sends an update for both keys at the same time the keyboard gets confused and show the wrong colour for one of the key. It's a wrong colour of the caps lock or the num lock don't show the correct state, but for both the internal state is still correct. So when it happens the colour of the num lock can be don't changed after the keys are pressed, then as soon as you press the caps lock key the num lock will show the correct colour and vice versa for the caps lock key but then it's a wrong colour instead. If the Tachyon mode is enabled it happens more frequently when if not.
It happens on a W1 too if the num lock is pressed with another (virtuel) keyboard.

**Reproduction**
1. Enable digital keys
2. Set the main colour of the caps lock key to white
3. Set the secondary colour of the caps lock key to black
4. Set the main colour of the num lock key to black
5. Set the caps lock key to unlocked an num lock to locked so that both are white
6. Press the caps clock and num lock key together
7. Check the colour of the cap lock and num lock, both should be black
8. Press the caps clock and num lock key together
9. Check the colour of the cap lock and num lock, both should be white
10. Repeat from step 6.

**Screenshots / Video**
no video

**System**
 - Win 10

**Versions**
- 1.28.1

**Keyboard Type**
- all

**Comment by Rocky04** [comment]
So because the system sends an message everytime one of the indication LEDs is changed and it contains the status of all the keys (num lock, caps lock and scroll lock) I assume there is a problem with the handling of the USB packages or that the keyboard don't prioritise the external state. Only the external state should be the valid one and the internal state should not computed at all. Because this problem should not exists normally, the last received message should always be the used one.


Because of this I believe that the handling of the indication state is interrupt based and that if there are two new messages in a short time, the handling of the later message are handled within the first one. So that the first one get started, than the second comes is and is finished and after that the first get finished, which causes the seconds to be overwritten from the outdated first one.

**Comment by PastaJ36** [comment]
Did some testing. The states itself of Num Lock and Caps lock are handled correctly. When you use the wave effect you can see that it does update to the right indication. I'm not a 100% sure yet, but I suspect it has to do with the way colours are updated. We don't update colours in ISR, but as part of the main loop because the I2C module is not ISR proof. There is something there that overrides the indication colours. 

That said, I don't think it's critical enough to dig deeper so I'm labeling this as wontfix.

**Comment by Rocky04** [comment]
What has the RGB effect to do with the problem? The indications isn't even used if a RGB effect is active as far as I know.

So if the RGB handling isn't ISR aware the problem is most likely because of this.

The whole USB sending and receiving is ISR handled (with callbacks). This would explain why the problem exists. If the Wooting receives two new packages for the indication LEDs directly successively, the RGB update from the first message would be interrupted from the second as mentioned. Depending on the timing the first RGB update get lost completly (this would explain the missed change) or within an update (this would explain the bad colour). It would also explain why it happens for often if Tachyon is enabled. So I think the problem isn't only limited to the indication update but there it's more obvious.


I can think of different solutions:
1. Pause all ISR when an I2C communication is performed. The problem is that then the USB communication is paused and to it will add an additional inconstistant input delay.
2. Update the LEDs asynchron, like on an additional chip which isn't effected from ISRs on the main chip.
3. Check if there is a control mechanism, typical chips that support SPI have a control mechanism to only apply an command after a special message is send to do so. So instead of directly applying the command as it is received it will only perform it when the it was sent completly.
4. Add a flag to indicate an interruption. Like add a global variable which is cleared before you send a LED update and which is set on every ISR routine. After the LED update was sent check if the value is still zero. If so you know that there wasn't any interrupt so that the update should be expected to be ok, if not you should perform it again.
(5.) Not recommended. Override all keys everytime when a new indication package is received.

**Comment by Rocky04** [comment]
With the SDK it happened for me from time to time that the RGB for the right side of the keyboard wasn't set correctly when I change the current profile.

Next it can happen that sometimes after the PC is started that all the LEDs are off even if keyboard works just fine (so no sleep bug occured).

**Maybe all these problems are related to this bug.**

**Comment by Rocky04** [comment]
Even I don't think that it's the root of this problem, the issue from https://github.com/WootingKb/wootility-issues/issues/19 most likely triggers this one so it happen more frequently.

**Comment by PastaJ36** [comment]
From your post on #19 , I checked and even if I only listen to the LED reports coming from the NKRO interface and ignore the other ones the bug still persists.

"What has the RGB effect to do with the problem? The indications aren't even used if a RGB effect is active as far as I know." 

Please read my previous post again and verify yourself. If you use the Wave effect you will not see this problem. The reason is that the Wave effect will continuously update the RGB part of the keyboard and thus will show that the status is set correctly in the keyboard. There is a bug in how the RGB updates after seemingly multiple status changes have come in.

There is no RGB update done in the ISR to avoid issues with I2C. Instead a refresh gets triggered and the next time the main loop gets to the RGB part it will just update the whole keyboard. I guess this is your number 5 solution. It just fits naturally within how the main loop operates, no flags or ISR pauses required.

**Comment by Rocky04** [comment]
Like mentioned in the starting post I knew that the internal state of the indication LEDs are correct. I haven't thought that you are using a RGB effect to test it and not just toggling the profile just once instead.

Because of the other fix the OS should not sent as much messages anymore it should become more unlikely to trigger this one and how this can be fixed was mentioned too.

**Comment by Rocky04** [comment]
I'm not able to reproduce the problem with the weird colour anymore under `1.28.3` (Alpha).
I can only reproduce the part where the update of one key is missed so that the colour of one gets changed but the other not.

_So even this bug isn't fixed it's at least a bit better now as it was expected..._

**Comment by Rocky04** [comment]
Maybe it would be good to set the message size to zero for the outgoing nKRO interface if it's disabled to avoid that the systems is sending LED update messages over this interface. So that there is always ony one outgoing keyboard interface active, the 6KRO or nKRO interface.

**Comment by simon-wh** [comment]
Appears to be fine in Wootility v4
