### ISSUE TITLE
switch profile with a different key

### ISSUE THREAD

**Issue by xanh18** [WootingKb/wootility-issues#212]
since a1 a2 a3 doesnt register on wootlity or wootomation as a keypress. i cant bind this to a different key like f13 or f14 to swap profile.

I want when I hit f13 to switch profile.

**Comment by simon-wh** [comment]
I'm a little bit confused by your request. In Wootility, you can just bind A1-A3 to whichever key on whichever layer you want in the Remap tab. Then you can activate it in whatever way you want

**Comment by xanh18** [comment]
Hey simon,

you're right with that. but with third party equipment we dont have acces
to that. e.g. with a elgato streamdeck I want to map a key to f13.

I should have added that, hope its more clear.

kind regards,

xanh

Op ma 15 mei 2023 10:22 schreef Simon W ***@***.***>:

**Comment by simon-wh** [comment]
The switching profile buttons only work on-board to the keyboard. You cannot currently switch the onboard profile using different software, unless you write something custom. So you'll need to configure the bindings to wherever they feel most comfortable on the keyboard using Remap in Wootility

**Comment by xanh18** [comment]
Hey simon,

thanks for the clarification.
Is it possible to add this to the backlog as a feature request. or are
there any concerns why this would not be preferable.

xanh


Op ma 15 mei 2023 10:53 schreef Simon W ***@***.***>:

**Comment by simon-wh** [comment]
It's certainly something that can be kept around as a feature request. It's actually a bit of an idea we had for Wootomation, to have the option to be able to change the on-board profile. So if that becomes available, then you'd be able to use Wootomation to change the keyboard profile to something when F13(or some other key/combination) is pressed

**Comment by xanh18** [comment]
Hey simon.

I didnt know it was already a feature request. im very glad to hear
that,and thanks for your quick reaponses on my emails. you can close this
ticket

xanh

Op ma 15 mei 2023 11:10 schreef Simon W ***@***.***>:

**Comment by simon-wh** [comment]
No worries :)

There hadn't been any ticket created for this idea already, but we've got one on the [Wootomation repo](https://github.com/WootingKb/wooting-macros/issues/150) now. So you can keep an eye on that to see when it's done 😄

**Comment by xanh18** [comment]
Awesome, thanks!

just saying. this was a "wish" from a streamer in the wooting discord. I am
mister squirtle from woothelp on there(ardenwenn). defenetly come say hi
once in a while :d

xanh

Op ma 15 mei 2023 11:24 schreef Simon W ***@***.***>:
