### ISSUE TITLE
Featuer Request: Wootility UI readibility improment

### ISSUE THREAD

**Issue by wilson97183** [WootingKb/wootility-issues#213]
**Is your feature request related to a problem? Please describe.**

In Wootility web's remap tab, some text has little bit confuse or readibility issue, 
1. Numpad and main area's enter looks same if didn't look at description
Normal: 
![image](https://github.com/WootingKb/wootility-issues/assets/81096404/27015008-7755-4ea8-a438-47f9ea914df6)
Hover on button: 
![image](https://github.com/WootingKb/wootility-issues/assets/81096404/b9f1a709-8713-4882-bd5a-7837f3f8ab0a)

2. Mouse botton 1~5 looks weird
![image](https://github.com/WootingKb/wootility-issues/assets/81096404/68dc4ecc-f4e4-4d5d-98a3-1183fdd6c8ff)

3. Numpad's decimal point and minus looks inconsistent
![image](https://github.com/WootingKb/wootility-issues/assets/81096404/ba7dca05-0332-4be4-810c-6b3d9a3f76ab)

**Describe the solution you'd like**

Change UI layout and some confusing/weird text

**Describe alternatives or workarounds you've considered**

leave it there because it's not critical issue, and trust user will read the description or using search bar to find out which button is what they want.

**Additional context**

In this [hackMD page](https://hackmd.io/@wilson1189/ryJbxfmS3), I listed something that I think can be improve and suggestion way to make thing better (still WIP)

### Additional information

**Platform information**
Windows 10 

**Wootility and Firmware version**
Wootility Web v4.5.5

**Keyboard Type**
N/A

**Comment by Doubs115** [comment]
Was also wondering why the look like that. I suggest that the mouse buttons be listed as M or MB 1-5. Then have the hover text give more context, right click, left click, forward, back, etc. This helps when going into configs of games so you can just match the number instead of needing to remember witch is which. That's just me or that tip could also be in the hover text. 

The rest seems like to just add num and click new line for the others. That's just my thoughts.

**Comment by neube3** [comment]
I would consider **this (and #146) not fixed**. Both light and dark themes are affected.

Tooltips are present (for some items - but not all misleading ones), while graphics are still weirdly out of line and inconsistent with others.

The ISO slash (of which I learned only in #146 just now) cannot even be found through a similar search (neither "iso" nor "slash" returns it). By brute-forcing input into the search field I learned it can be found as "stripe". It has no tooltip either.

Wootility v4.5.5 (Desktop)
OS: Windows
Device: Wooting Two HE ARM, v2.6.22

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/60be663f-f595-48a7-8219-59c30a2044e3)

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/cc0c81e5-18dd-4cbb-b678-83068c2a8ebe)

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/e283512c-a584-42d4-a22c-2f9c89ec3272)

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/b86c0650-9ea7-4931-a69d-9d4d33aea033)

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/7a23e47e-003e-40dc-abdf-cadddcbeecb7)

![image](https://github.com/WootingKb/wootility-issues/assets/18572821/628615f9-31c2-46a7-923b-efd4fbd73121)

It is worth noting that preset names have both bigger "keys" (buttons, areas - at my res and windows' zoom level they're 75 px vs regular keys' 50 px) therefore can hold more content, but they _also_ use a slightly smaller font. 
Below we can see W, C, D from keys (bigger) compared to those from "Workman", "Colemak", "Dvorak" profiles (smaller).
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/adcd5e46-9284-45b4-9643-393b96c898ba)

More inconsistencies that were not reported previously, but as I started digging jumped at me:
1. `J` glyph. While I can understand that "Q" goes under the base line for the glyph, J seems just completely out of whack:
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/d1230843-5a64-4827-9b7b-347e0cb37f79)

2. Extended characters group has different base line for glyph than the Basic characters group:
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/b79b5ea2-9a3d-48ad-88ac-1a4971b58124)

Just to be clear, an ad-hoc visualisations of how I would see the affected keys fixed. 
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/29e7708c-806b-4000-bd48-f3b6f0bef44b)
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/3462733c-fa04-4a3b-9246-a8337279028e) 
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/4b4a0bf9-2f56-4ff2-b195-15b9f347ac7b)
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/583a686e-5e63-4ce9-a356-9c968a5f4414)
![image](https://github.com/WootingKb/wootility-issues/assets/18572821/c5723a08-edd7-49c7-b2d7-1176921dd2ca)


Extended characters group needs their glyphs moved just a pixel up on all keys to be consistent - I think.

**Comment by simon-wh** [comment]
@neube3 The patches that resulted in this issue being closed are not present in the Wootility version you're using. You need to use the beta (See #wootility channel in the Wooting Discord)

**Comment by neube3** [comment]
Indeed they are! This, somehow, was not obvious to me.

@simon-wh Maybe it would be possible to add some kind of "fixed in beta" label/status so this kind of thing doesn't happen again? ;)
