### ISSUE TITLE
Failure in RBG effects

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#22]
**Describtion**
Pressing the numpad "6" key while using the trail or ripple effect causes an additional effect on the escape key.

**Reproduction**
1. Open the Wootility
2. Select the ripple effect
3. Press the key "6" on the numpad

**Screenshots / Video**

**Desktop (please complete the following information):**
Win 10

**Wootility and Firmware version**
128.2

**Keyboard Type**
Wooting Two

**Comment by simon-wh** [comment]
Appears to be resolved in v4
