### ISSUE TITLE
Removing FN Layer 2/3 keymap can remove the color profile of the previous layer

### ISSUE THREAD

**Issue by mikey-dg** [WootingKb/wootility-issues#239]
I also noticed this and I'm not sure if it should go into separate issue but when I delete that FN2 layer mapping it triggers removal of FN1 layer colors.

_Originally posted by @Uiasdnmb in https://github.com/WootingKb/wootility-issues/issues/200#issuecomment-1522575332_

I just ran into this, and figured it should have its own issue open.

Description:
When removing an FN layer from the Remap tab, the Wootility always removes the highest-index FN layer from the Colour tab as well, whether or not there are the same number of layers in each.  Notably, adding a keymap layer does not add a color layer, but removing a keymap layer will always remove a color layer, with no check for a corresponding index.
It does not seem to matter whether or not changes have been saved to the keyboard, and this problem is observed when working with both active and inactive profiles.

Workaround:
Fortunately the undo functionality restores the lost color layer, but also the deleted keymap layer.  To remove a keymap layer without removing a lower-index color layer, you have to first create a blank corresponding FN layer in the Colour tab.

1. Go to the Wootility Remap tab and create 2 FN layers
2. Go to the Colour tab and create 1 FN layer, optionally changing key colors to identify it
3. Remove FN layer 2 from the Remap tab, noting that this removes FN layer 1 from the Colour tab

Versions:
Wootility v4.5.5
Wooting 2 HE v2.6.22

**Comment by simon-wh** [comment]
Hey, this auto closed as I merged the internal PR to fix this. The fix will be included in the v4.6.14 release
