### ISSUE TITLE
Regarding the problem that the lights cannot be adjusted

### ISSUE THREAD

**Issue by wangwangsir** [WootingKb/wootility-issues#247]
There are four buttons whose lights cannot be adjusted.they are “6”“y”“h”“b”.
This problem does not affect the normal use of the keyboard, but it has a serious impact on the appearance.

1. Reinstalling the driver cannot solve the problem.
2. Turning off all lights doesn't solve the problem
3. Updated to the latest wootility 4.6.7, but it cannot be solved.

https://github.com/WootingKb/wooting-double-movement/assets/149142271/cb916428-8481-4819-9e5b-98c0081b7fd0

![970ac5216577b1d1a071706e8c212ca](https://github.com/WootingKb/wooting-double-movement/assets/149142271/21dfae37-e12b-4815-a662-67711964757c)

**Comment by PastaJ36** [comment]
This looks like a hardware issue. Probably some RGB LED's have a short. Can you send us an email for a replacement PCB? social@wooting.io
