### ISSUE TITLE
Wooting 60he cannot work 

### ISSUE THREAD

**Issue by yliannnnnng** [WootingKb/wootility-issues#259]
Initial Problem:

Keyboard began acting erratically, with automatic key presses and typing.
Attempted a reboot and software update to resolve the issue.
Subsequent Issue:

RGB lighting on the keyboard stopped working.
All keys became unresponsive.
Suspected the device might have entered restore mode.
Attempted Solutions and Encountered Difficulties:

Reset Process:

In the "Waiting for update mode to connect" step, obtaining keyboard authorization was successful.
Connection Issue:

In the "Waiting for device to be connected" step, encountered a problem:
A pop-up window indicated no devices were available for use.
Troubleshooting Attempts:

Tried using different PCs and cables.
The issue persisted regardless of the change in hardware.
Technical Details:

Wootility Version: v4.6.11 (Web)
Operating System: Windows
motherboard B560M PRO-VDH WIFI
![S__1318969](https://github.com/WootingKb/wootility-issues/assets/152938021/707d41d6-94e7-417d-9f6b-2e30cc0333ff)
![S__1318970](https://github.com/WootingKb/wootility-issues/assets/152938021/d2bde962-77bc-4fb8-a7b8-3994407bb6cd)

**Comment by simon-wh** [comment]
Hi,

Sorry to hear that you're having issues. Although this github repository is more for bugs and feature requests, it's not really intended for technical support which looks like you need.

It looks like you've already tried the main things that I would've suggested to you, so I would recommend contacting our official support to get help with your issue as you may have a faulty keyboard. Our email is: `social@wooting.io`, please include all the details you have posted here in your email as well as your order number.

I hope you're able to get your issue sorted quickly. Thanks, Simon
