### ISSUE TITLE
Fn key get trapped in a strange state after being toggled and then entering and exiting another function layer.

### ISSUE THREAD

**Issue by mingxuanqin** [WootingKb/wootility-issues#266]
**Describe the bug**
When the `Fn` key is used as a toggle key, it will be stuck in a whitely lit state after entering and exiting another function layer from the "toggled to" Fn1 layer.
- The Fn key in this state kind of looks like an activated caps lock, However, its colour is not affected by any setting in Wootility: it is always white.
- The Fn key in this state no longer works as intended, after pressing it once, everything goes back to normal (both its colour and function).
- This only occurs when Fn is used as toggle key, not when manually holding the key.

**To Reproduce**
Steps to reproduce the behaviour:
- Set the `Fn` key to toggle key; 
- Tap the Fn key to switch to the Fn1 layer;
- In this state, try entering and exiting the Fn2 layer (by pressing and releasing the `Fn2` key);
- After exiting the Fn2 layer, the keyboard returns to the main layer, with the `Fn` key now lit white;

**Wootility and Firmware version**
Wootility v4.6.12-beta (Web)
OS: Windows
Device: Wooting 60HE ARM, v2.7.3-beta.2

**Comment by YourSandwich** [comment]
Same issue here, I want to use the Mod Tap function on the FN 1 Key.
So when I hold FN then it is activated and when I tap it, it should toggle the FN Key.

EDIT: What happens is, it switches to FN 1 Layout and I can only switch back by pressing a different FN Lock.
When I'm back to the Main Layout, the FN Key is white, as described in the issue.

**Comment by simon-wh** [comment]
Could you try out using the latest v2.8.0 firmware? I fixed various issues with using the Fn key inside of a Toggle Key and it should behave correctly now

**Comment by YourSandwich** [comment]
@simon-wh looks good!

**Comment by simon-wh** [comment]
> @simon-wh looks good!

Great! I'll close this issue then :)
