### ISSUE TITLE
Keyboard and Wootility lock up with Razer Chroma Connect enabled

### ISSUE THREAD

**Issue by DFrye333** [WootingKb/wootility-issues#27]
**Describe the bug**
Shortly after enabling the Razer Chroma Connect functionality through the Wootility, both the keyboard hardware and the Wootility software lock up and fail to respond until the keyboard is power-cycled (disconnected from and then reconnected to the PC).

**To Reproduce**
1. Enable Razer Chroma Connect through the Wootility keyboard settings.
1. Minimize the Wootility to the OS taskbar.
1. Re-open the Wootility from the OS taskbar using "Show Wootility" from the program's context menu.
1. Test the keyboard's responsiveness to input, and Wootility's responsiveness (e.g. by attempting to navigate around the program).
1. Repeat Steps 2-4 repeatedly until responsiveness tests fail.

**Desktop:**
 - OS: Windows 10 (1909 18363.815)
 - Motherboard: MSI Z87-GD65

**Wootility and Firmware version**
- Keyboard firmware version: 1.27.3
- Wootility version: 3.4.6

**Keyboard Type**
Wooting Two

**Comment by Rocky04** [comment]
How long do you need to foce the problem, like how constant can you reproduce it?

I guess this is related to that issue: https://github.com/WootingKb/wooting-rgb-sdk/issues/16

**Comment by DFrye333** [comment]
> How long do you need to foce the problem, like how constant can you reproduce it?

Doesn't take me very long at all; just a few repetitions is usually enough to do it. I've only tried enabling Chroma Connect a few times now, but the issue has occurred each time, so it seems reasonably consistent.

> I guess this is related to that issue: [WootingKb/wooting-rgb-sdk#16](https://github.com/WootingKb/wooting-rgb-sdk/issues/16)

Could be, but it's worth mentioning that when I say that the hardware and software "lock up", I mean entirely. It's not just lighting color changes - I can't use the keyboard, at all, even simply to type, until it's power-cycled. Wootility is completely unresponsive as well, even the title bar (e.g. window minimize/close button), until the power-cycling. Maybe that was clear and is a symptom of this other issue you're referencing as well, I'm not sure.
