### ISSUE TITLE
Automatically Adding Fn Layer 2

### ISSUE THREAD

**Issue by Jameson-Shijing-Liu** [WootingKb/wootility-issues#276]
Description:
When I connect my keyboard, Wootility will automatically create a new Fn Layer 2 for the Digital Profile. This is potentially supposed to be an Easter Egg of some sort, as it has “EPIC GAMER MOVE” written in the middle which is clearly intentional (see <img width="799" alt="Screenshot 2024-03-04 at 23 19 48" src="https://github.com/WootingKb/wootility-issues/assets/131400221/5c8dead9-a77d-4644-b922-454251776d96">). The issue with this, aside from being unwanted, is that this layer binds Fn 1 to the bottom right key, meaning that it overwrites whatever key I have there in Fn Layer 1.

Steps to reproduce the behaviour:
1. Connect keyboard to computer (after disconnecting if already connected).
2. Observe described issue.

Setup Information:
Wooting 60HE+ Module (ISO)
Wootility v4.6.15
Firmare 2.7.2
M1 Pro MacBook Pro 14″ 2021
macOS Sonoma 14.3.1 (23D60)

**Comment by simon-wh** [comment]
This issue has already been fixed and is present in firmware v2.7.2-beta.3. 

Thanks for the good issue report regardless!
