### ISSUE TITLE
Failed Wooting One update from v2.7.2 to the latest v2.8.1

### ISSUE THREAD

**Issue by Lembugila** [WootingKb/wootility-issues#288]
**Describe the bug**
I get the error "An error occured while completing the update
Make sure you follow the steps below, then try to restart updating your device."

I get the message box of:
1
Ensure you have a working internet connection
2
Ensure Wootility isn’t being blocked by your firewall
Users in China may have issues downloading firmware updates due to the Great Firewall

This occurs on the Windows version and the web version of the latest Wootility v4.6.20 when trying to update the Wooting One from the firmware version v2.7.2 to the latest v2.8.1

**To Reproduce**
Try to update a Wooting One firmware version  v2.7.2 to the latest v2.8.1 using Wootility v4.6.20 or Web version

**Screenshots / Video**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - If USB problem: N/A

**Wootility and Firmware version**
Wootility version v4.6.20 or Web version

**Keyboard Type**
Wooting One English

**Comment by simon-wh** [comment]
Hey, thanks for the report.

I've narrowed down the issue and have a patch ready. I'll be releasing a new Wootility shortly with the fix 😁

**Comment by simon-wh** [comment]
I've released Wootility v4.6.21 which fixes this. It is currently available on the Web builds, desktop will be coming shortly
