### ISSUE TITLE
Drops frames and no turbo building

### ISSUE THREAD

**Issue by Echo0n30Fps** [WootingKb/wootility-issues#295]
**Describe the bug**

**To Reproduce**

**Screenshots / Video**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - If USB problem: Motherboard type

**Wootility and Firmware version**
Find in your Wootility Settings

**Keyboard Type**
Wooting one or two + language

**Comment by neube3** [comment]
@Echo0n30Fps Please, edit the issue because now it's just a copy-paste of the template with a different subject. Not helpful at all and will definitely not be enough to lead the developers to coming up with a fix for your problem.

**Comment by PastaJ36** [comment]
Closing it until details get added
