### ISSUE TITLE
Remap keys for JIS

### ISSUE THREAD

**Issue by ellemonchy** [WootingKb/wootility-issues#298]
**Is your feature request related to a problem? Please describe.**
There is no key setting for JIS as shown in the red frame in the attached image in Wootility's remap settings. e.g. Yen mark, Kana, and so on.

**Describe the solution you'd like**
A key for JIS will be added to the Remap settings.

**Describe alternatives or workarounds you've considered**
N/A

**Additional context**
Wooting 80HE supports JIS keycaps, so I hope Wootility supports them as well.

**Platform information**
Windows 10

**Wootility and Firmware version**
Wootility Web v5.0.0-alpha

**Keyboard Type**
Wooting 80HE JIS

**Comment by ellemonchy** [comment]
I attached the missing JIS keys.[
![PXL_20240926_025221258 MP](https://github.com/user-attachments/assets/78f31df1-8004-4588-b625-244abd71fd74)
](url)

**Comment by simon-wh** [comment]
At least for the Yen symbol and \, the Int 3 and Int 1 keys that are the default remap keys for those are supposed to behave like that. Do they not behave correctly for you?

How do you have your keyboard layout configured in Windows? I noticed in my testing that these keys would not be functional unless you were using the Japanese IME keyboard (although I would assume that's what you're using)

**Comment by simon-wh** [comment]
Btw, I just noticed that Wootility wasn't showing the new Remap keys for JIS as options. I had hidden them at some point in v4 as the firmware for that wasn't capable of it, but forgot to restore them. With the latest build of v5, you should be able to see:

You'll be able to see
- Int1 - Int6 (Which are all directly from the HID spec, Int3/Int1 are the ones I was able to find to be the relevant JIS inputs from those, i.e. the split backspace key and the split r-shift key).
- Hatakana, Hiragana and Zenkaku/Hankaku keys (Which are Lang3, Lang4 and Lang5 in the HID spec)

Hope this helps!

**Comment by ellemonchy** [comment]
Thanks for ur reply.
And yes, the Key bindings for JIS were not displayed in the Wootility UI remap settings.
So Yen symbol is work at default profile,  but it is displayed blank on Wootility.(see attach image)
And then, if I remap other keys and save in this state, the Yen symbol will no longer work.
BR,
![remap setting](https://github.com/user-attachments/assets/329642b7-f3dd-4090-a5d2-716e853c0a3e)

**Comment by ellemonchy** [comment]
And thanks, I can see the Int 1/3 settings on wootility UI now.
Due to the above problem, I think the Int1/3 mapping should be reflected in the default profile as well.
Most Japanese keyboards should have Int1 next to Backspace and Int3 next to R-Shift.
BR
![wootility settings_jis](https://github.com/user-attachments/assets/ad79cf20-a5ae-4ef1-b193-7fa0c0f3ebea)

**Comment by simon-wh** [comment]
Thanks for getting back to me.

The default remap configuration does include Int 1 and Int 3, but I think it wasn't showing them properly before due to the them being hidden in Remap.

Do they all behave as expected for you? The Kana key as well?

**Comment by ellemonchy** [comment]
Int1/3 are working, but the JIS keys below don't seem to be working.
・Ime On/Off - Looks like the same behavior as Caps.
・Katakana, Hiragana, ZenkakuHankaku - There was no behavior.

**Comment by simon-wh** [comment]
Hey, sorry for not giving an update. I take it you seen the latest Wootility v5 build which includes a further revision on the JIS keys?

Is everything behaving as expected now?

**Comment by yoshiok** [comment]
#357
