### ISSUE TITLE
Issue: Huge delay on single DKS events

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#3]
# Wootility Version
xx

# Firmware Version
xx

# Keyboard type
all

# Issue description
Each single occurance of a key press where the release happens on the same state, causes a huge delay because the keyboard actively waits a few milliseconds to send the key up event.

# Steps to reproduce
1. Open Wootility
2. Connect any keyboard
3. Select an anlog profile
4. Open DKS settings
5. Add bindings for a single state (circle)
![image](https://user-images.githubusercontent.com/5910569/69059655-34d2a600-0a16-11ea-9774-54b93c1a68b7.png)

# Explanation
![image](https://user-images.githubusercontent.com/5910569/69060460-ac550500-0a17-11ea-95d6-8123ee74a7c5.png)
For the first key "1" it took 45 ms for the key up.
For the second key "2" it took 6 ms until the key down and 54 for the key up.
For the third key "3" it took 5 ms until the key down and 54 for the key up.
For the last key "4" it took 6 um until the key down and 53 for the key up.
So for all the keys it took 224 ms just for one column.

# Possible fix
The keyboard should sent the key up in the next possible slot, which is after 1 ms (the next polling intervall). If this time is to short for the OS to register it, the handling must be implemented asynchronous so it don't causes a delay to its handling (not easy to implement).
All single key presses should be handled together and not sequently.

**Comment by DarrenVs** [comment]
I believe this issue contains similar problems as the one mentioned here
https://github.com/WootingKb/wootility-issues/issues/2

**Comment by Rocky04** [comment]
Besides limited to DKS I don't see a similarity.

 - The single events are always in order, the holding events aren't.
 - The single events aren't combined together, the holding events are.


On the other side I would I would use the same approach to fix both. Havind a delay of 1 ms between each row.

**Comment by simon-wh** [comment]
This should be resolved with the DKS update, v4.3 which is now out in beta
