### ISSUE TITLE
Bind a pair of hotkeys to another pair of hotkeys

### ISSUE THREAD

**Issue by jerrygreen** [WootingKb/wootility-issues#305]
**Is your feature request related to a problem? Please describe.**
I want to bind an entire hotkey on another hotkey? For example, I want to bind FN+P to ALT+P (for example).

**Describe the solution you'd like**
In Wootility, we are already able to rebind KEYS, but it would be so cool if we had a feature to rebind entire HOTKEYS.

**Describe alternatives or workarounds you've considered**
There are additional third-party software like AutoHotkey, HotkeyBind etc. A lot of them. But they're third-party and aren't saved to keyboard. I'd like Wootility to have similar settings and save it directly onto keyboard.

Currently it is possible to rebind like: <kbd>FN+SOMETHING = SOMETHING</kbd>. It's not only limited to FN key (not supporting alt, ctrl, shift), it's also impossible to bind a key pair to it. I wanted to do: <kbd>FN+SOMETHING = ALT+SOMETHING</kbd> <--- this one is not possible!

**Additional context**
It might be additional layer types like this:

![image (21)](https://github.com/user-attachments/assets/cba405cd-4d72-42bb-b410-aaeedc44722a)

![image (23)](https://github.com/user-attachments/assets/6ac0270d-9832-4431-8575-0fe651c5ffee)

So I can choose to which particular layer I want to add hotkey: CTLR, ALT, SHIFT, FN, CTRL+ALT, etc

As you can see, in this particular layout, where I do have arrows, I don't really have alt on the right side of keyboard. Therefore, I need to use both my hands for a hotkey like ALT+P. I'd like to bind that to FN+P so I can use my single hand for that. And it would be cool if it's a built-in feature and saved to keyboard.

### Additional information

**Platform information**
Every platform: Windows/MacOS/Linux

**Wootility and Firmware version**
Wootility v4.7.2 (Web)
OS: Windows
Device: Wooting 60HE+, v2.9.1

**Keyboard Type**
60HE Ansi (US)

**Comment by BigBrainAFK** [comment]
In Wootility V5 we allows DKS bindings and other advanced keys on the FN layer so you can bind any combination of 4 keys on the fn layer.

**Comment by jerrygreen** [comment]
Huh, it seems particularly for <kbd>Fn</kbd> keybind pairs it's actually possible to make such a bind using DKM feature, indeed!

For now, it's just what I want!

And since on right side of keyboard I only have <kbd>Fn</kbd>, I come up with that I don't really need other options. DKM is enough for me. Thanks!
