### ISSUE TITLE
Problems with the DirectInput controller support on Win

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#31]
**Describtion**
_Because this is still often a topic on the helpdesk channel I want to write a short summary about the DirectInput problem._

Every change of the interface order (and so every toggle of the XInput state or manually disabling of an interface) will cause mixed-up joystick IDs resulting in a wrong display of the joysticks controls of the Wooting or other devices and problems in games. The problem is that Win assign a joystick ID to every HID controller interface but never delete it if the interface on this index number isn't a controller anymore. The systems knows how many joysticks are present and searches for the first joystick IDs in the Registry where the interface is active. Because of that the system often assign an interface from the Wooting for a foreign controller or a wrong interface from the Wooting to the backward interface of the Wootings Xbox controller.

In addition the ordering in the Registry for the DirectInput controllers typically don't matches the USB order (for me it's mixed-up as long as XInput is enabled).

The following indices are the sub-keys for me for the DirectInput interfaces which are stored under the key `HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\DirectInput\VID_03EB&PID_FF01\Calibration` for a W1. As shown the order is totally mixed-up and inconistent between different devices if XInput is enabled. For the same device as long as nothing has changed the order is consistant (same revision number) but it still can happen from time to time that the order changes due to some strange unknown circumstances.
```
Wooting One (Xinput enabled)

Index of DirectInput sub-key   USB Interface number   Function
------------------------------------------------------------------------------------------------
*                              MI 01                  6KRO (not present because it's a keyboard)
0                              MI 04                  Media part 1
1                              MI 04                  Media part 2
2                              MI 05                  classic gamepad
3                              MI 02                  Configuration
4                              MI 06                  RAW
*                              MI 03                  nKRO (not present because it's a keyboard)
5                              MI 00                  Xbox controller

Wooting One (Xinput disabled)

Index of DirectInput sub-key   USB Interface number   Function
------------------------------------------------------------------------------------------------
*                              MI 00                  6KRO (not present because it's a keyboard)
0                              MI 01                  Configuration
*                              MI 02                  nKRO (not present because it's a keyboard)
1                              MI 03                  Media part 1
2                              MI 03                  Media part 2
3                              MI 04                  classic gamepad
4                              MI 05                  RAW


Wooting Two (Xinput enabled)

Index of DirectInput sub-key   USB Interface number   Function
------------------------------------------------------------------------------------------------
0                              MI 02                  Configuration
1                              MI 06                  RAW
2                              MI 05                  classic gamepad
*                              MI 03                  nKRO (not present because it's a keyboard)
3                              MI 04                  Media part 1
*                              MI 01                  6KRO (not present because it's a keyboard)
4                              MI 04                  Media part 2
5                              MI 00                  Xbox controller

Wooting Two (Xinput disabled)

Index of DirectInput sub-key   USB Interface number   Function
------------------------------------------------------------------------------------------------
*                              MI 00                  6KRO (not present because it's a keyboard)
0                              MI 01                  Configuration
*                              MI 02                  nKRO (not present because it's a keyboard)
1                              MI 03                  Media part 1
2                              MI 03                  Media part 2
3                              MI 04                  classic gamepad
4                              MI 05                  RAW
```

**Reproduction**
1. Open the Wootility and toggle the XInput feature in the settings menu.
2. Check the Registry value for the sub-keys of the key `HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\PrivateProperties\DirectInput\VID_03EB&PID_FF01\Calibration`.
3. Where should be 6 sub-keys in it (index 0 to 5).
4. If the current XInput state is enabled only one sub-key should contain a value `Joystick Id` and if not only two but there are at least three.

**Know workaround**
Applying the Registry fix from: https://wooting.helpscoutdocs.com/article/56-fix-controller-settings-under-windows

**System**
 - Windows (10)

**Versions**
 - all

**Keyboard Type**
 - all

**Comment by Rocky04** [comment]
_So now about to the possible solutions._

In short I don't think this problem can be really completely fixed in a good manner. For this it's necessary to separate the controller interfaces from all other interfaces. So that not even disabling of sub device can cause wrong assignments of joystick IDs. For that the Xbox controller and the classic controller need an individual vendor and product ID combination but this is only possible with a custom (upper) filter driver or a more advanced MCU which can act like multiple devices. _Most likely because of this even MS has changed how the Xbox One controller driver works. Instead of providing the virtual backwards interface via the driver to the same vendor & product ID combindation (VID_045E&PID_02FF) they are using a filter driver to create that for a different ID (VID_045E&PID_02FF)._


**Possible solution which will at least reduce the chances that the joystick IDs got messed up**
1. Faking a Xbox One controller instead of a Xbox 360 controller. So that there is only one controller ID assigned to the Wooting. -> Very hard to do and there is still the problem when the state of that feature is toggeled.
2. Instead of alternating the serial number, the product ID can be changed. -> By owning a vendor ID this is the simplest solution to reduce the chances that the joystick IDs got mixed-up. Then there isn't a device change depeding of the XInput state anymore. But it can still happen as soon as sub devices are disabled or out of the sudden.
3. Creating a custom driver just for Win. -> Not easy to do properly and the users need to install them. But only the ones who cares aboput that / have the problems need to do it.

**Comment by PastaJ36** [comment]
Thanks for the detailed description Rocky. 

Just wanted to confirm here we've seen people having trouble updating on Windows because of this issue. The workaround listed solves that issue.

**Comment by Rocky04** [comment]
After I wiped my device informations for the Wooting One and connected it again the order with XInput enabled was the same as for the USB interfaces. So again, this isn't constant and I can't tell why or what's influencing it.

Yeah, if I remember it correctly in rare cases it can even cause problems with the general broken input and a non-working Wootiltiy connectivity.


By the way, having a separate product ID would also help with Steam. Now Steam hides the classic controller part of the device so because of that it's not accessible in Steam. I think the reason is that Steam had detect the Xbox 360 interface via the hardware survesy and so it's removing not just the DirectInput interface for this (for the backward compatibility interface) but also for the classic controller. This handling is just coupled to the vendor and product ID combination, so as soon as other IDs are used the classic controller appears again.

**Comment by PastaJ36** [comment]
Interesting. It seems that the whole serial + USB version is not respected by everybody. So in general it would be best if we just have unique product ID for different interface setups right? Any downsides to that approach?

**Comment by Rocky04** [comment]
It depends, for the general things on the different OSs it works and only for the old controller support for Win (DirectInput API handling stored in the MediaProteries in the Registry) it don't work. Because there it only differ devices instances by vendor & products IDs to separate them but not anythign else.

As mentioned the best way would be that only controller interfaces or non controller interfaces are in a vendor & product ID combination. So that the type is truebred and not like the Wooting where they are mixed together. But the only way to separate them is by using an upper filter driver so the controller data can be exluded in the kernel and injected into a virtual device, like the Xbox One controller handles it. But this would require the user to install a custom driver, but only people with problem would need that.

Even it won't fix the problem I think it would help a lot to reduce the problems for the users if there are different product IDs depending on the controller changes. The downside is that a single device can use multiple product IDs. Like if you also allow later on to disable the classic controller (DirectInput) on the Wooting the same way as the Xbox controller you would end up in four product IDs (all off, all on, just XInput, just DirectInput) for a single device. Because of this the system would hold an unique state for each instance like it does now for the two serial numbers.

**Comment by PastaJ36** [comment]
I was thinking about this issue again. What if, instead of removing the xinput interface, we replace it with a dummy interface? Just like how we do with NKRO/6KRO, but then also without the dummy interface triggering the xinput driver. This way we guarantee the same order without any more invasive actions. I don't see any particular downside to it, what do you think? @Rocky04

**Comment by Rocky04** [comment]
A had mentioned that dummy interface before but avoided it because as, mentioned it can happen that the order of the interfaces can be mixed anyway.
So a dummy interface don't make things better normally but the chances to make it worse are high. Like if the interfaces are in order the XInput interface is the last one. If so everything is fine because then it's missing and so can't cause trouble. The only benefit for a dummy interface is when multiple Wooting of the same product are used.

Again I think the best option right now is to change the product ID depending on the XInput state. Then the interface cout will stay always the same. Also this should help with Steam because then the classic controller should appear again if XInput is disabled.

**Comment by PastaJ36** [comment]
> A had mentioned that dummy interface before but avoided it because as mentioned it can happen that the order of the interfaces can be mixed anyway. It would only help if the interfaces are mixed up and you would know the order which you can't.

Oh really? That is strange, because we do define the interface numbers as part of the USB descriptor. Have you seen the interface numbers get mixed up? If so, wouldn't that always cause an issue with the Joystick ID?
 
> Again I think the best option right now is to change the product ID depending on the XInput state. Then the interface count will stay always the same. Also this should help with Steam because then the classic controller should appear again if XInput is disabled.

Alright, I agree that's the best solution. Was just thinking about how to avoid having to use multiple PID's for every device we'll make with Xinput

**Comment by Rocky04** [comment]
> Oh really? That is strange, because we do define the interface numbers as part of the USB descriptor. Have you seen the interface numbers get mixed up? If so, wouldn't that always cause an issue with the Joystick ID?
For an example have a look on "Wooting One (Xinput enabled)" of start post. I can't tell what causing it but it can happen and yes it will cause issues with the joystick ID for sure when it happen. This isn't a device but rather a Win thing.

The dummy device would only help if it's a joystick interface otherwise the IDs are still bad. A dummy interface would help to keep the interfaces count constant but this only helps if multiple Wootings of the same type are used but a different product ID would archive that too.
