### ISSUE TITLE
Keyboard is always spamming inputs for analog profiles

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#32]
**Describtion**
It's more a minor thing but the keyboard spams analog and digital inputs all the time as soon as an analog profile is selected. Only on the digital profile the keyboard sent messages if something has changed. So I don't get why this behaviour is differently on an analog profile where the Wooting always spams digital messages even when the digital keys are disabled and no DKS bindings are present. I would imagine that handling all the USB interrupts need more compute power than using the same algorithm to prevent spamming on the digital mode. I get why the analog inputs are spammed as long as a binded key for a stick is pressed but even if no key is pressed the keyboard spams messages with zero values.

**Reproduction**
1. Select an analog profile, the type doesn't matter.
2. Disable the digital keys.
3. Start scaning the USB data with Wireshark.
4. Filter the data to only show the keyboard data `(((usb.endpoint_address == 0x83) || (usb.endpoint_address == 0x86)) && !(usb.data_len == 0))`
4. Press a random key which isn't bind, like `X` for a keyboard on complete default settings.
5. You will see multiple keyboard messages with not keypresses as long a key is pressed.
(6.) Also the keyboard will always send analog messages even if no key is pressed if you enlage the filter for them.

**Media**
Every intervall (8 ms) a message is sent even if there is no input at all.
![image](https://user-images.githubusercontent.com/5910569/84168252-79d42d80-aa77-11ea-99c2-042d171a59ee.png)

**Systems**
 - all

**Versions**
 - all

**Products**
 - all

**Comment by PastaJ36** [comment]
I tried reproducing this issue today. I can use the same filters to see the keyboard USB data.

While I can see in Analog mode I get the continuous messages for the Analog interface, if I filter those out I don't see any difference in my digital keys. They just go on and off like normal.

You mention: "You will see continuous messages for the analog interface with only zero values and also for the keyboard interface.", does that mean you see a spam of digital keys as well?
