### ISSUE TITLE
Overwriting profiles doesn't clear DKS

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wootility-issues#33]
Thanks DarrenVs#0001

**Describe the bug**
When your Active profile has DKS bindings, and you replace it with a Inactive Profile that doesn't have DKS bindings on the same key, it will not clear the DKS from the replaced profile.
However Wootility can't see it, causing ghost like behaviour.

**To Reproduce**
1. Add DKS binding(s) on your Active Profile with the following binding
![](https://cdn.discordapp.com/attachments/344031355803271179/721750480425975808/wootility-beta_FtP1BZqmMh.png)
2. Drag an Inactive Profile clear of DKS bindings to replace your Activce Profile
3. Press the key that used to contain DKS
4. Your key should now behave like your DKS binding is still there, yet Wootility can't see the binding

**Screenshots / Video**
https://cdn.discordapp.com/attachments/344031355803271179/721750571144445992/2020.06.14-17.12.mp4
> Pressing H will now say HEY with 0 DKS bindings

**Work around solutions and side effects**
- Pressing the reset DKS button will disable the glitched out 'ghost' key entirely until you switch modes to fix it.
- Adding a new DKS binding on the same key and removing it fixes it.

**Comment by Rocky04** [comment]
Theoretical this is a doubled post, see https://github.com/WootingKb/wootility-issues/issues/6
