### ISSUE TITLE
Dragging switching keys can cause accidental removal of the key

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wootility-issues#35]
Thanks DarrenVs#0001

When dragging keys around in the Remap UI, you have to be pixel accurate. Otherwise you may lose a key in the process when dropping the key between two keys.
It might be better if the key hitboxes were wide enough to not leave a gap between them when dragging and dropping them around.

https://cdn.discordapp.com/attachments/344031355803271179/721759815344324658/2nwD1e6luH.mp4

**Workaround**
- `Ctrl + Z` to undo the mistake and attempting it again

**Comment by PastaJ36** [comment]
This is on purpose. We're assuming a user with mouse is very precise, so it will not happen too much on accident. We already made them a little bit bigger than shown, but I don't think we have to overlap them fully.

**Comment by simon-wh** [comment]
A thought that crossed my mind was the approach of having a delete button similar to the profile management. Or at least not deleting an assigned key unless it's dragged out of the keyboard area

**Comment by Rocky04** [comment]
I would also prefer to long right clicking to delete a binding or to drag & drop it outside the keyboad.

**The problem here isn't to be pixel precise with a mouse in general, the problem here is to do that without even seeing where the actual mouse position is because you can't see through the dragged key.**

**Comment by DarrenVs** [comment]
### My take on it:
Out of instinct I right click keys, or drag keys away from the keyboard to 'throw them away'. In my use experience I found it impractical and slower to drag keys and wedge them in between two keys.

However; with the clean UI there are some areas of the UI where I also expect that the keys do get removed. 

Here's a rough sketch on the areas where I believe keys should be deleted when dropped:
![image](https://user-images.githubusercontent.com/2780639/84802900-84576f80-b001-11ea-82c9-aeab694065d4.png)

*Gif demonstrating both actions, 'right-clicking' and 'dragging' keys to remove bindings:*
![DLgYiiMKhg](https://user-images.githubusercontent.com/2780639/84801310-4b1e0000-afff-11ea-88f6-703f436b04ed.gif)

**Comment by Rocky04** [comment]
1. Give every key an oversized zone
2. If two oversized zones are overlapping each other check which key is near (just use the left / upper one if the distance is equal)

_So every key will have the oversized zone, even the other ones._

**Comment by DarrenVs** [comment]
> the gab between F4 and F5 

@Rocky04 Thanks for mentioning it
I adjusted the image to fill the gaps

**Comment by PastaJ36** [comment]
Slightly increase the invisible drop boxes, looks pretty good now

![image](https://user-images.githubusercontent.com/7443105/84903916-fb970d00-b0ae-11ea-893c-ecb5c794d4d9.png)

**Comment by PastaJ36** [comment]
Releasing this in 3.5.7

**Comment by DarrenVs** [comment]
I can still replicate this problem after I resize Wootility

![Ud1uPRBZPA](https://user-images.githubusercontent.com/2780639/85922236-26891a00-b882-11ea-86e5-2e418ccad9ca.gif)

There seems to still be a tiny gap when you make Wootility fullscreen

**Comment by Rocky04** [comment]
_And this is the reason why I had suggested a dynamically handling..._
