### ISSUE TITLE
Missing possibility to bind the "rudder" from the simulation controls in the Wootility

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#39]
**Describtion**
It's a minor thing because the support of the simulations controls is strange anyway. They aren't supported on Win (only throttle is used as the slider because that is missing) while on Linux (openSuse) two more are supported (accelerator & the missing rudder, but some time ago all five were supported under https://html5gamepad.com/).
So in the JSON for the inactive profiles the rudder control is present and can be binded manually but it's not possible to bind that via the Wootility.

**Reproduction**
1. Use Linux as the OS
2. Import profile with share code: "0cb9ff30-d826-4010-9594-a2c74e89d306"
3. Check the controller bindings
4. The key "V" is manually binded to the rudder but that isn't shown in the Wootility, instead the key is shown as a blank key
5. Open https://html5gamepad.com/ and press the "V" for the imported profile the analog value will be shown

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/5910569/84964721-231cc280-b10d-11ea-84e8-02a9a21e8940.png)

**Systems**
- all

**Versions**
- all

**Type**
- all

**Comment by Rocky04** [comment]
_Also, there is a bug in the current Beta so the second characters for the number keys from the number row are shown._

**Comment by simon-wh** [comment]
This is resolved in Wootility v4
![image](https://user-images.githubusercontent.com/10797576/122202264-c9bcb000-ce94-11eb-9f19-a4664c379b7e.png)
