### ISSUE TITLE
Issue: DKS bindings are separated and can't be used comprehensively

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#4]
# Wootility Version
xx

# Firmware Version
xx

# Keyboard type
all

# Issue description
If a key is used on multiple DKS bindings, like a modifyer to run in a game, they are handled separatly and not comprehensively. Like if "shilft" is bind for the four movement keys, it's not registred if one key is realeased even if all the others are still pressed.

# Steps to reproduce
1. Bind "shift" for "W", "S", "A" & "D" for a deep press only (state 2 - 3)
2. Bind "W", "S", "A" & "D" to itself for the whole key travel (state 1 - 4)
![image](https://user-images.githubusercontent.com/5910569/69063236-6fd7d800-0a1c-11ea-8d86-a27d88414768.png)
3. Press "W" and "A" together fully down
4. Let "A" go but still hold "W" fully down
5. "Shift" is released instead of still hold

# Possible fix
Don't handle each DKS separatly and combine the results of all pressed keys together.
Add a second buffer (all ones) which represent where a key up needs to be forced (zero for these keys), like for a single key press.
Then combine the two buffer (with logical and) and sent the result. On the next cycle a forced key up should be gone so the other key down can be registered again.

**Comment by simon-wh** [comment]
This should be resolved with the DKS update v4.3
