### ISSUE TITLE
3/5 pages in the profile editor have click indicators that don't do anything

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#44]
**Describe the bug**
The Digital Settings, Analog bindings, and Analog Settings pages have click indicators on the pointer device when hovering on the keyboard, But clicking doesn't do anything

**To Reproduce**
1. Go to one of the following pages `Digital Settings`, `Analog bindings`, or `Analog Settings`
2. Hover your pointer device over the keyboard
3. Notice your pointer device icon changing to a click indicator
4. Attempt to click for a action, but nothing happens

**Video**
![sOTXUh7BFA](https://user-images.githubusercontent.com/2780639/85278338-1db0d680-b485-11ea-8497-b2227e30d356.gif)

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware versions**

- Frimware: `1.29.0`
- Wootility: `3.5.7-alpha`

**Keyboard Type**

- Wooting One

**Comment by PastaJ36** [comment]
Good idea to make this consistent

**Comment by DarrenVs** [comment]
For the `Analog Bindings` page you could make right-click remove bindings

I have actually tried doing that a few times because of the DKS habit

**Comment by Rocky04** [comment]
*About the right click for the remapping, I would prefer a long click for unbinding and a short click for reset the key binding back to default.*

**Comment by DarrenVs** [comment]
The idea of having a way to restore/undo a individual key on the remapping page back to default does sound nice. But preferably not as a short right click. I prefer having right-click as the consistent way remove things in Wootility.

I also don't know of many user interfaces that use a long-press feature in keyboard&mouse setups.
A better way would probably be to right-click on a empty field to restore a key to the currently saved key.

We should probably open a separate issue as a feature suggestion for discussing. It does sound like a nice thing to have

**Comment by Rocky04** [comment]
Would also work, then an user just need to double click for reseting.

**Comment by PastaJ36** [comment]
I think the need for back to default is better done by having the undo across the Wootility. Problem with some back to default is that it is hard to indicate what you're returning to.

**Comment by Rocky04** [comment]
But reset to default is completely different than undo the last changes. If you want to change a key later on, undo would make no sence since you would lose all the steps after. Meaning often it would be much easier to search the key and manualler set it back to default. Like if that was 5 changes ago, you would need to redo the last 4.

Why? You already have the default settings for all the keys (and layers) hardcoded into the keyboard. So I would call these the defaults which a right click on an empty key would set them to.

**Comment by simon-wh** [comment]
No longer applicable in Wootility v4
