### ISSUE TITLE
Changing theme or language kicks you out of the settings page

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#45]
**Describe the bug**
After updating or restoring your Firmware; When you change theme or language in Wootility, it automatically kicks you out of the settings page. This feels like weird behaviour as I might not be done checking out all the settings.

**To Reproduce**
1. Restore or Update your keyboard Firmware 
2. Pick a new theme or language
3. Notice that you are no longer in the settings page

**Video**
![kfjMMOeU5Y](https://user-images.githubusercontent.com/2780639/85278866-d4ad5200-b485-11ea-9eb8-91b767f9e021.gif)

**Workarounds**
- Restart Wootility after updating to avoid the issue

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware versions**
- Frimware: `1.29.0`
- Wootility: `3.5.7-alpha`

**Keyboard Type**
- Wooting One

**Comment by PastaJ36** [comment]
This is a weird issue, I've seen it happen before. The problem is that it doesn't always happen. I just installed the new alpha and it works fine. Can you check if there's any error when you open the Wootility with cmd? `%appdata%\programs\wootility-alpha\wootility-alpha`

**Comment by Rocky04** [comment]
So I wasn't able to reproduce that either.

So please save all data relating to Wooting `%USERPROFILE%\AppData\Roaming\wootility-alpha` and delete all the data in it and test it again. I would assume it's working then. If so you should delete the data again and copy the backup data back in. If it's not working after that we know it's some weird user data, then it would be great if you can provide that data to Wooting so the bad setting can be identified.

**Comment by DarrenVs** [comment]
After some more 'monkey testing' I figured out that this issue only occurs after you update or restore the Frimware.
I can preproduce this in Alpha, Beta, and Live versions of Wootility.

I have updated the issue with it's "**To Reproduce**" steps.

**Comment by simon-wh** [comment]
Not applicable to Wootility v4
