### ISSUE TITLE
Remapping - Resizing Wootility offsets the anchor point of dragging keys

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#47]
**Describe the bug**
When the Wootility window is resized from default, dragging keys will no longer be in the center of the cursor

**To Reproduce**
1. Go to the remapping page and drag a key
2. Note the anchor point of the dragging effect
3. Now make your Wootility fullscreen
4. Notice the anchor point has moved away from the center

**Video/Picture**

*Default window size*
![image](https://user-images.githubusercontent.com/2780639/85921870-af528680-b87f-11ea-8bd5-5dc8c310d3fd.png)

*Fullscreen window*
![image](https://user-images.githubusercontent.com/2780639/85921789-0d329e80-b87f-11ea-8a98-9d614423e7c3.png)

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware versions**
- Firmware: `1.29.1`
- Wootility: `3.5.8-alpha`

**Keyboard Type**
- Wooting One

**Comment by Rocky04** [comment]
Maybe it would be better if that anchor point is fixed more on the top left of the dragged object, then resizing should change it and it would be maybe better to precisly drop the key. Like then the top left point of the object can be used as the possition to indicate where the mouse is.

**Comment by DarrenVs** [comment]
I think my preferable method would be that Wootility remembers from what offset you started dragging, and that it respects that offset instead of snapping the key towards your pointer device

**Comment by Rocky04** [comment]
Then there is still an user experience problem about the correct mouse possition. **Of course this can be fixed if the dragged obejct becomes opaque as long as it's dragged.**

**Comment by PastaJ36** [comment]
The draggable key implementation is a little tricky, so it's hard to keep the same offset from where you started. An issue point can be a key with a different size, like the left shift or ISO enter. You would need to calculate some relative offset and then add that to the draggable. 

I made the center position dynamic, so at least it's consistent on different Wootility sizes now
