### ISSUE TITLE
Can't rename profiles in some profile configurations

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#50]
**Describe the bug**
You cannot rename profiles that have Digital Keys disabled or make major use of DKS. The profile's settings do not allow you to type correctly while renaming the profile.

**To Reproduce**
1. Create a profile with Digital keys disabled |***or***| Create a profile that unbinds WASD using DKS
2. Double click on the profile to start renaming it
3. Try to type
4. Notice DKS or Digital keys prevents you from renaming the profile

**Screenshots / Video**

*Here I'm trying to rename the default profiles that come after a restore or when you first get your keyboard*
![wWupT4E6OI](https://user-images.githubusercontent.com/2780639/86513043-4fbc2400-be07-11ea-81c3-4729c042cf7b.gif)

*Trying to rename a profile where I unbound WASD using DKS*
*Attempted to write down "My personal profile", "Hello world!"*
![ZJp7eFncJG](https://user-images.githubusercontent.com/2780639/86513099-ac1f4380-be07-11ea-9d9d-a8fdafb936ba.gif)

**Workarounds**
- Toggle to Digital profile using the Mode key after starting the profile renaming interface
- Enable Digital keys and save your keyboard settings before renaming, and then disable Digital keys again
- Remove all your DKS settings that hinder your ability to type, and re-insert them after renaming

----

**Desktop**
 - OS: Windows 10

**Wootility and Firmware version**
- Wootility: `3.5.9-alpha`
- Firmware: `1.29.1`

**Keyboard Type**
- Wooting One - ANSI

**Comment by Rocky04** [comment]
_For me the basic background about this is intended, like if you don't want to type on that profile you should also not be able to rename it._

**_My thoughts on this..._**
But yes, there should be a way to change a profile without even set it as the active one. Like not only for renaming but also for all the other actions. For this there should be an indication which profile is active on the keyboard (like by having a symbol left or right to the profile name) which can be different than the current selected one in the Wootility. Like the profile selection can be have two zones, one small one to change to that profile on the keyboard there also the indication symbol is and a large section for the name where you can select the profile just in the Wootility to set it up.

**Comment by PastaJ36** [comment]
I was thinking about this issue. It will be pretty hard to implement some override behaviour just for renaming, but there's something else we can do. A problem we have now is that it's impossible to rename a profile without also selecting it, thus making it impossible to rename these analog and DKS profile.

What if we add a rename option to the three dot menu? This will both solve this issue and be a nice enhancement to renaming in general.
![image](https://user-images.githubusercontent.com/7443105/86531451-a1c18000-bec1-11ea-8962-65eb91ab5bb9.png)

**Comment by DarrenVs** [comment]
I think the best, easy solution would be to make the keyboard go into the Digital profile when editing profile names, and then switch to the profile after editing

*Editing a profile, switching to digital mode to be able to type, and then back to the profile after releasing/submitting textbox focus*
![MgU7XoyLk2](https://user-images.githubusercontent.com/2780639/86531640-527c4f00-bec3-11ea-987f-ff401624efd6.gif)

**Comment by Rocky04** [comment]
I'm not very comfortable if the Wootility would automatically switches profiles if the profiles are renamed, so I prefer the option to add a renaming action to the options list. But as mentioned I think the best option is to separated editing from the active profile in general.
