### ISSUE TITLE
Can't change RGB Fx properties

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#52]
**Describe the bug**
The Wootility UI doesn't respond to changing RGB Fx, not allowing you to adjust the settings

**To Reproduce**
1. Make sure Tachyon mode is disabled
2. Change to a new RGB Fx profile containing different Fx properties
_RGB Profile now changes on the physical keyboard, but no indication in Wootility_
3. Notice that you cannot adjust the RGB Fx properties

**Screenshots / Video**
![dKHa0B8qSn](https://user-images.githubusercontent.com/2780639/87181271-50aaf500-c2e2-11ea-962e-f4fc7f2472d7.gif)

**Workaround**
- Restart Wootility after selecting and saving a RGB Fx profile

---

**Desktop:**
 - OS: Windows 10

**Wootility and Firmware version**
- Wootility: `3.6.0-alpha`
- Firmware: `1.29.1`

**Keyboard Type**
- Wooting One - ANSI

**Comment by simon-wh** [comment]
Thank you so much for the report! Discovered it was down to a very minor issue and have sorted it
