### ISSUE TITLE
The Input Box UI of Analog Bindings feels unresponsive

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#54]
**Describe the bug**
When binding Analog Bindings in Wootility, there's often a long delay before the Input Box responses to your input.

**To Reproduce**
1. Go to Analog Bindings on a Analog Profile
2. Click on a binding, and press a key to bind it to
3. Notice how long it takes for the Input Box to respond to the input

**Screenshots / Video**
![SGYA9pkqe5](https://user-images.githubusercontent.com/2780639/87184423-44c23180-c2e8-11ea-96c1-8e2454018acf.gif)

**Workaround**
- Press the same key twice

---

**Desktop:**
 - OS: Windows 10

**Wootility and Firmware version**
- Wootility: `3.6.0-alpha`
- Firmware: `1.29.1`

**Keyboard Type**
- Wooting One - ANSI

**Comment by DarrenVs** [comment]
The text "Press A Key" also gets cut short

**Comment by simon-wh** [comment]
Hmmm, interesting, I was unable to replicate it on Linux. Have yet to try it on Windows, but it doesn't strike me as something that would have different behaviour on different platforms

**Comment by PastaJ36** [comment]
Is this in alpha or public as well?

**Comment by DarrenVs** [comment]
I can no longer replicate this issue on Alpha, nor Live

**Comment by PastaJ36** [comment]
Should we close until we can replicate again, or leave it open? Not sure what's best in this case.

**Comment by DarrenVs** [comment]
I think closing it until we have more info on it to reopen the issue is fine
