### ISSUE TITLE
The Input Box of Analog Bindings has unreadable text

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#55]
**Describe the bug**
When binding keys in a non-maximised window, the text indicating what to do gets cut short

**To Reproduce**
1. Go to Analog Bindings in a Analog Profile
2. Make the Wootility window small (if not already)
3. Click a binding to start binding
4. Notice the text being cut short

**Screenshots / Video**
![AqRagdNSN9](https://user-images.githubusercontent.com/2780639/87184980-43453900-c2e9-11ea-9627-a26e669b75e5.gif)

---

**Desktop:**
 - OS: Windows 10

**Wootility and Firmware version**
- Wootility: `3.6.0-alpha`
- Firmware: `1.29.1`

**Keyboard Type**
- Wooting One - ANSI

**Comment by simon-wh** [comment]
Not applicable to Wootility v4
