### ISSUE TITLE
Calculator Character onto numlock doesn't work on Win10

### ISSUE THREAD

**Issue by RyanChomistek** [WootingKb/wootility-issues#57]
**Describe the bug**

I remapped the num lock key to open the calculator, and it doesn't open the calculator. I can remap the calculator to other keys (like numpad 7)

**To Reproduce**

On wootility, go to remap. 
then go to function layer
then drag the calculator character to numlock

**Desktop (please complete the following information):**
Windows 10

**Wootility and Firmware version**
Your Keyboard is running firmware version: 1.29.1

The Wootility is version: 3.5.11

**Keyboard Type**
Wooting 2 American English

**Comment by Rocky04** [comment]
@RyanChomistek **This seems not to be a general bug.** _Or it's just related to ANSI which is unlickely._ I can rebind the num lock key to whatever key I want on my W2 ISO and it's working as expected. So I can bind it to the calculator and the calculator app is started by pressing that key.

So I assume that maybe you num lock key isn't correclty working or there is some problem with the internally keyboard settings for the remapping of that key. So you should check if the num lock is working in general and with other bindings to it. Maybe try a restoring.

**Comment by simon-wh** [comment]
I was unable to replicate this issue on both Linux & Windows using an ANSI Wooting Two in the following scenarios:
- Numlock bound as normal on `Main Layer` and Calculator bound to NumLock on the `Function Layer`
- Calculator bound to Numlock on both layers
- Calculator being bound on any other key

When you re-open Wootility does it still show as being bound on the Numlock key? What exactly does your mapping look like? 

I got the impression from your post that it works when bound to any other key, but not if on Numlock, is that what you were saying?

Thanks

**Comment by RyanChomistek** [comment]
huh ya now it works fine
