### ISSUE TITLE
Remap - UI lag while dragging keys

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#58]
**Describe the bug**
When picking up a key and dragging it over to the keyboard it lags behind the cursor.
This is probably due to a inefficiency when dragging keys over other keys as this doesn't happen when dragging over an empty area.

**To Reproduce**
1. Go to Remapping
2. Go to All Characters
3. Pickup a key and drag it over to the keyboard
4. Notice the delay between the key moving over to your cursor

**Screenshots / Video**
![AKWu3wsByT](https://user-images.githubusercontent.com/2780639/87234135-5251e700-c3ce-11ea-83cb-ef6ac5dd9360.gif)

---

**Desktop**
 - OS: Windows 10

**Wootility and Firmware version**
- Wootility: `3.6.0-alpha`
- Firmware: `1.29.1`

**Keyboard Type**
- Wooting One - ANSI

**Comment by simon-wh** [comment]
Hmmm, this could be down to it doing checks with every key that you pass over with the mouse. When dragging a key it's not really necessary to have any of those effects or checks, so could disable the area while dragging which may prevent the lag

**Comment by Rocky04** [comment]
Yes, it's much slower when you are over other keys but even if there are none it's lagging behind a bit.

**Comment by PastaJ36** [comment]
Interesting, seems like too many rerenders caused by the dragging. 

You can see a character in all characters "activates" (get the orange border) sometimes. That doesn't have to happen. I guess if we disable drag events for those keys we'll get a nice performance boost.

**Comment by DarrenVs** [comment]
I can still replicate this issue on the Keyboard UI

![IxKGIGn1v1](https://user-images.githubusercontent.com/2780639/88087593-70b3a180-cb89-11ea-876f-b9dd75dcdef4.gif)

**Comment by Rocky04** [comment]
Yeah, it's pretty fast now over the character on the bottom, a little bit slow over the empty spase and very slow of the keyboard scheme.

_I guess this is due to the fact that over the keyboard it always checks for a possible swap of the keys / the hover effect._

**Comment by DarrenVs** [comment]
I believe in places like this Canvas can be a very powerful tool.
There should be libraries available for react to make working with Canvas easier. Might be worth looking into to solve issues like these. Maybe also allowing that experience to expand into more visually dynamic elements such as playground or simulated RGB effects inside Wootility.

**Comment by PastaJ36** [comment]
The main issue here is React triggering renders when you hover over the keys. There is a callback that gets triggered when your mouse enters the key and when your mouse leaves the key. These are used to update which keys will get swapped in when you drop the key. We could possible optimise how React updates these keys, but I don't feel it's worth it.
