### ISSUE TITLE
Lock key indicators still toggle after sending WOOTING_COLOR_INIT_COMMAND

### ISSUE THREAD

**Issue by Kristallranke** [WootingKb/wootility-issues#59]
**Describe the bug**
After issuing the WOOTING_COLOR_INIT_COMMAND, the color states of the keys should be host controlled only.
However when pressing one of the lock keys (e.g caps lock) the indicator toggles to active.
Pressing caps lock again on the other hand doesn't reset the indicator, so the color remains unchanged.

**To Reproduce**
1. Use the Wooting RGB SDK
2. Call wooting_rgb_kbd_connected()
3. Press num lock

Screenshots / Video
![VID-20200714-184904](https://user-images.githubusercontent.com/7579599/87453993-a8f43680-c603-11ea-875a-326f76081b6a.gif)

**Desktop:**
 - OS: Windows 10

**Wootility and Firmware version**
Firmware: 1.29.1

**Keyboard Type**
Wooting Two, ISO German

**Comment by simon-wh** [comment]
I've resolved it to our intended behaviour, which is lock indicators will not be disabled when using the RGB SDK (hope that is what you expect), will be out with the next firmware update.
