### ISSUE TITLE
View for sub menus can get out of box

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#61]
**Describtion**
The UI parts of the sub menus aren't correctly shown anymore as separate fixed viewboxes if tabulator is used to change the current active element. The content of the sub menus are all togethere in one wide page, by pressing on the sub menu the view slides to the correct area. But if tabulator is pressed often enough the wide page is moved but without keeping the fixed viewport. The reason is that element has have the focus even you can't see it and by pressing tab the next element in line will get the focus which causes UI to move the slider so that element is on the screen.

**Reproduction**
1. Open Wootiltiy
2. Select an analog profile
3. Go to the sub menu colour settings
4. Click on the RGB effect mixing
5. Press tab two times

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/5910569/87523408-2f9e2780-c687-11ea-94e5-9589974790fd.png)

**Systems**
- Win 10

**Versions**
- 3.5.11

**Type**
- not applicable

**Credits**
- Thanks to PyrdePavkki from Discord

**Comment by DarrenVs** [comment]
Can replicate the same issue on the Remapping page

![image](https://user-images.githubusercontent.com/2780639/87541493-9e887a00-c6a1-11ea-8a2e-9276dae916b0.png)

**Comment by PastaJ36** [comment]
That is just beautiful, how did he find this. Wonder what a nice way to solve this is

**Comment by Rocky04** [comment]
I expect per exident. The bug report small a little bit short, have a look here: https://discord.com/channels/167181566978555904/590898276182523955/732863171768877069

In case it's not clear, it also works with `shift` + `tab` to access the previous element...

I imagine the fix will can be simple, here are some solutions I can think of:
1. Remove the possibility to fucus on all elements, I expect there is no reason at all to go through all elements anyway by tab.
2. Add and order the tab IDs for the elements to control the focus per view box and add a check to control them. So to maybe save for each view box the first ID and last ID and save which is the current view box. Then you can check if the next tab ID is still in the same view box and so re-route the current element which has the focus. Like if the first element has tabID=20 and the last 30 for the sub menu "analog bindings" and this is the current active sub menu you can check if tab is pressed on the element with ID 30 and so jump to 20 again. And or course the other way arround if the user pressed shift + tab on element 20 to jump to 30. The problem here is to handle it before the focus is changed so that the view port don't get changed. To avoid a strange key handler for this you can add dummy elements as the first and last element for the view box. Then as soon as the first is reached you only need to jumpt to thelast but one element (because the last is a dummy) and as soon as the last is reached you need to jump to the second (because the first is a dummy).
3. Instead of having a wipe sub page which contains all sub menus split them into separated pages. But you have maybe problems to have the animation as now if the sub menu is changed.

**Comment by simon-wh** [comment]
No longer applicable to v4.3
