### ISSUE TITLE
Razer integration isn't working if installed on the fresh

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#63]
**Description**
On a fresh installation the Razer Chroma integration isn't working. It worked on the latest versions in my VM where the Wootility and Razer software was updated a few times by now. But on a fresh installation it wasn't working with the current Wootility (3.5.X), on the older Wootility (3.4.X) everything is fine. _Due to this it seems it has something to do how the Wootility is registrated and that there is a problem with the newer versions with that. Also on the newer version it seems that the status indication for that feature is broken when minimized. When the feature is enabled but the Wootility is minimized the check mark is not set._

**Reproduction**
**_The Razer software must be never installed before on the system._**
1. Install Razer Synapse 3 with the module connect and studio
2. Install the Wootility 3.5.12
3. Enable the Razer integration in the Wootility
4. Notice that the Wootility isn't shown in the Razer software and so it's not working
5. Uninstall the Wootility and install the Wootility 3.4.6
6. Enable the Razer integration in the Wootility
7. Notice that the Wootility is shown now in the Razer software and is working

**Screenshots / Video**

**Systems**
 - Win 10

**Versions**
- 3.5.11 & 3.5.12

**Type**
- all / not applicable

**Comment by simon-wh** [comment]
I was unable to replicate this issue. I set up a fresh Windows VM and followed the steps as you mentioned, installing Razer Synapse with those modules and ran Wootility, everything appeared to work as expected. Wootility showed up in the Chroma Connect device list in Synapse immediately

**Comment by Rocky04** [comment]
The bug is still present for me...

Installed Wootility 3.5.12 then Razer Synapse 3.5.730.72314 and then activate the Razer integration in the Wootility. Sadly the Wooting entry didn't appear.

**Comment by simon-wh** [comment]
Have discovered that the issue is due to the Visual C++ Redistributable 2015-2019 being missing from the system (which I had indecently installed on my VM before testing thus not being able to replicate). For now, if you experience this issue, you can install it manually from [here](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads). Future updates for Wootility will automatically try and install it if it's missing

**Comment by Rocky04** [comment]
I can confirm that installing the framework and a reboot after that fixes the problem.

So I assume the DLL / framework was present on the older version? Because you mentioned that nothing has changed...


The bug that the enabled state of the feature isn't show on the context menu is still present for me. When I enable the Razer integration in the Wootilty while it's maximized and then minize it the check mark isn't shown.

**Comment by simon-wh** [comment]
@Rocky04 Hmmm, I'm still unable to replicate that issue on my test environment where I was able to replicate it not working without the redistributable, very strange. Do you get it on the 3.6.0-alpha as well? We're thinking we may clean that up the refactor from that and throw it in v3.5 beta as it should give a much more solid basis

**Comment by Rocky04** [comment]
_For completeness because this was discussed privately..._

Toggling the Razer integration can cause a child process of the Wootility to be killed. If that happens the tray state can be decoupled and so don't show the real state and can also cause the window to become completely white (on Alpha 3.6.1) or that the app can't be correctly fully closed (Stable 3.5.12) because the main process still survive.

This happens as long as the Razer software is installed and I wasn't able to force the child process to be killed when the Razer software was uninstalled. _To test that I copied the Razer DLLs into the system32 folder so I can still toggle the integration._
