### ISSUE TITLE
AppImage system icon not showing

### ISSUE THREAD

**Issue by TjayNL** [WootingKb/wootility-issues#68]
**Describe the bug**
So i'm using the Linux AppImage directly downloaded from the website. However the Wooting Icon isn't showing in the system menu.

**Screenshots / Video**
[view image](https://ibb.co/McHZZzb)

**Desktop (please complete the following information):**
 - OS: Nitrux OS (Ubuntu based distro)
 - DE: Plasma 5
 - If USB problem: none

**Wootility and Firmware version**
Wootility 3.5.12 (AppImage)

**Keyboard Type**
Wooting one

**Comment by simon-wh** [comment]
Hmmmm, strange, I'll set-up a VM later on with that distro and see if I can replicate & debug it.

**Comment by Rocky04** [comment]
The icon wasn't shown for me on openSUSE too.

**Comment by PastaJ36** [comment]
We were able to fix the icon in the system tray in 3.6. As for the icon of the AppImage file itself, we couldn't find a way to add an icon to it.
