### ISSUE TITLE
Wrong analog output when partly binding the thumbstick axis to the keyboard

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#7]
# Wootility Version
3.3.3

# Firmware Version
1.27.3

# Keyboard type
Wooting One

# Issue description
Registering only part of one of the thumbstick's to the keyboard will cause the missing axis to be pressed down 100%

# Steps to reproduce
1. Open Wootility
2. Create an analog profile and only partly bind the thumbstick axis (as shown below)
![KUQM4SYZov](https://user-images.githubusercontent.com/2780639/70874120-0d3d1200-1fb1-11ea-9fd4-bc0708d75535.png)

3. Open a [gamepad tester/debugger](https://html5gamepad.com/)
4. Notice that the analog output is stuck on the missing axis

# Pictures / Video of problem
**(Click for video controls)**
[![Click for link to imgur](https://user-images.githubusercontent.com/2780639/70874001-76705580-1fb0-11ea-85b9-0469e52620c7.gif)](https://i.imgur.com/nzmqwxd.mp4)
#### Result:
![GFj5imh1wo](https://user-images.githubusercontent.com/2780639/70874040-acadd500-1fb0-11ea-9ec8-5f610865aeab.png)

**Comment by Rocky04** [comment]
I think it would be great if a partial binding of an anlog axis can be used to influence how the values are behave.

Like if only the upper part of an axis is used a key press will start from 0 and go up to the maximum possitive value and if only the lower part is used then the value will start from the maximum negativ value and go up to zero. The implementation can be very easy.
https://discordapp.com/channels/167181566978555904/195657629060694016/619167213940899894

**Comment by PastaJ36** [comment]
Fixed this, will be added to the full programmability release. Thanks for the info.

**Comment by Rocky04** [comment]
Fixed in Wootility 3.5.0 and firmware 1.28.1.
