### ISSUE TITLE
Feature Request: Add idle brightness option for trail effect

### ISSUE THREAD

**Issue by waruyama** [WootingKb/wootility-issues#70]
Currently there is no option to set idle brightness for the trail effect. I think this effect is the most appealing, but due to the missing idle brightness I cannot use it in a dimmed room. If technically possible, please add idle brightness to this effect.

![image](https://user-images.githubusercontent.com/43434568/99561016-cfb5e580-29c6-11eb-88c8-0a0620150dcb.png)

Also, please consider not limiting the idle brightness to 30%.

**Comment by PastaJ36** [comment]
Good idea, think we should add this

**Comment by simon-wh** [comment]
This has been added in Wootility v4.2, will leave this open until Wooting One/Two support has been re-integrated into v4

**Comment by simon-wh** [comment]
We've just released Wootility v4.3 and we're aiming for v4.4 to be the update that brings up Wooting One/Two support. I'm gonna close this now as not really much reason for it to stay open now
