### ISSUE TITLE
Changing the active profile updates the keyboad lighting despite being locked by the RGB SDK

### ISSUE THREAD

**Issue by Kristallranke** [WootingKb/wootility-issues#75]
Changing the active profile updates the keyboard lighting despite being locked by the RGB SDK.

1. Prepare profiles with two different color settings
2. Call wooting_rgb_kbd_connected()
3. Change profiles
4. the color changes according to the active profile

Firmware: 1.29.3
Wooting Two (ISO German)

**Comment by Rocky04** [comment]
I think this should be better placed here: https://github.com/WootingKb/wooting-rgb-sdk/issues

Also there is a use-case for both possibilities, so a parameter to control if the RGB should be changed or not on a profile change would be maybe a good idea. Like an app can only control just a few keys for status indication while the others should still match the current profile.

There are also workarounds possible, like to send commands to the keyboard from time to time to check if something has changed on the keyboard side. Or to switch to a more lax mentality, like often for any other external decoupled thing which don't actively inform the other side about a change, were every now and then a complete refresh is done and not just sending the changes all the time. _Of course this approach may adds a huge overhead to it..._

_The Wootility does that by having to commands, first it sends "ActivateProfile" to change the profile while the RGB stays the same and then "LoadRgbProfile" to load the RGB colors for new profile._

**Comment by simon-wh** [comment]
While I agree with your suggestion of the use-case of controlling just a few keys for status indication and still wanting the rest to match the current profile. It doesn't necessarily work with how things work currently, as the profile switch will override all the colours, not just the ones that are set. The way the RGB SDK works right now, there's no real way to maintain these 'overlay' colours on top of the profile, as it just sets the colour for the LED directly. Although, I can think of some ways to work around this, not perfect, but I think that kind of behaviour is something I'll try take a look at down the line with RGB SDK improvements from Lekker.

For now, I've implemented a fix which makes the current behaviour make more sense, so changing profile while the RGB SDK is active will not override any of the colours already set. Will be in the next release
