### ISSUE TITLE
RGB "Scan" effect initializes at 0 keys

### ISSUE THREAD

**Issue by bustinbung** [WootingKb/wootility-issues#76]
**Describe the bug**
When selecting the "scan" mode on a new profile, the default width setting is 0 keys.

**To Reproduce**
1. Create a new profile
2. Select "scan" as an effect
3. Width is now 0 keys

**Screenshots / Video**
[Video](
https://user-images.githubusercontent.com/22670587/104109651-28568000-529e-11eb-92b7-fae6eec68826.mp4)

**Desktop (please complete the following information):**
 - Windows 10 Pro 20H2

**Wootility and Firmware version**
- Wootility v3.5.12
- Firmware v1.29.3

**Keyboard Type**
Wooting two ANSI

**Comment by simon-wh** [comment]
Issue has been fixed in dev & will be available in the next beta release
