### ISSUE TITLE
Handle Fortnite Strafing + DirectInput

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wootility-issues#86]
One potential use-case for DirectInput is to use with XIM Apex to use it on Console.

Currently, the Fortnite Strafing option only applies to XInput but makes no mention of it. So we should set it up to mention that it only works for XInput or allow DirectInput to use it as well. The tricky thing with setting it up with DirectInput is that the Axis' / Joystick are not super well defined

**Comment by simon-wh** [comment]
For the next beta release, we'll have a note added about it only supporting Xbox Controller mode. I'm keeping this issue open for tracking the actual support of this option on DirectInput

**Comment by RphSam** [comment]
Hi, is this done? Eagerly waiting. Still cant get straffing with xim. (Xim support direct inpit only)

**Comment by Rocky04** [comment]
This is linked to point 4 of another feature request and so most likely currently under development. Hopefully it will come with the next update.

See: https://github.com/WootingKb/wootility-issues/issues/106.

**Comment by simon-wh** [comment]
This has been added in Wootility v4.3
