### ISSUE TITLE
Ability to remap mouse buttons

### ISSUE THREAD

**Issue by simon-wh** [WootingKb/wootility-issues#87]

**Comment by PastaJ36** [comment]
Is very useful for Fortnite to setup double bindings for faster building (Disclaimer: need some help from Fortnite player to describe it better)

**Comment by flybearteddy** [comment]
Yes, some fortnite players rebind their mouse bind on to a keyboard button to make certain gameplay mechanics work. If we were to bind the keyboard bind on to the mouse instead there would be a delay. This is the only way to keep both double edit binds and scroll wheel reset on fortnite.

**Comment by simon-wh** [comment]
We've added Left, Right, Middle mouse buttons as well as 4,5 has been included in the latest beta release, v4.3
