### ISSUE TITLE
Feature request: Link to the release notes or changelogs within Wootility

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#89]
# Description
I updated my Wootility, but for some reason the release notes do not appear.
Would be nice if the user could have a direct link to the [release notes](https://wooting.io/blog/wootility-v36-update-notes), or re-open the release notes window through a button.

## Concept
![image](https://user-images.githubusercontent.com/2780639/108108868-79be1000-7091-11eb-922c-5a6418c19475.png)
![image](https://user-images.githubusercontent.com/2780639/108110254-4c726180-7093-11eb-9b93-1617c0ba638c.png)

**Comment by simon-wh** [comment]
A button to re-open the patch notes has been added on the bottom left of the settings window in Wootility v4.3. Although, we may move the position in future
