### ISSUE TITLE
Caps Lock indicator doesn't work on Mac OS

### ISSUE THREAD

**Issue by adammw** [WootingKb/wootility-issues#9]
**Describe the bug**
Caps Lock indicator doesn't work on Mac OS.. Pressing Caps Lock correctly activates Caps Lock but there is no change in colour when activated.

**To Reproduce**
Steps to reproduce the behaviour:
1. Plug in to mac OS computer
2. Press Caps Lock key
3. See built-in / Apple keyboard indicator light up, Wooting keyboard does not.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6

**Wootility and Firmware version**
Wootility version 3.3.3
Firmware version (latest as of 31-12-2019)

**Keyboard Type**
Wooting one - US / Korean gaming edition

**Comment by Rocky04** [comment]
Because I can't test this, you had set the secondary colour of the key to a different colour then the primary one, or?

**Comment by Rocky04** [comment]
@adammw
Because I can't test this, you had set the secondary colour of the key to a different colour then the primary one, or?

*Like in this example there the primary colour is green and the secondary colour is red.*
![image](https://user-images.githubusercontent.com/5910569/71773751-265b3200-2f63-11ea-82a8-056c6be539ee.png)

**Comment by PastaJ36** [comment]
Thanks for the report. I've tried to verify it with my macbook and it works correctly. The color changes on my built-in keyboard and Wooting keyboard at the same time. Do you have any other external keyboards you can use to verify this issue?

**Comment by adammw** [comment]
I get random issues where it sometimes works and sometimes doesn't. I'll need to investigate further.

**Comment by adammw** [comment]
OK. i believe that i've isolated the issue to software on my computer rather than any issue with the keyboard itself. 

Mac OS X seems to filter out accidental CAPS LOCK presses so you need to press for a certain amount of time for it to activate. Further, it seems that CAPS LOCK is per-keyboard, in that you can independently have caps lock on one keyboard and not on another. Adding into the mix, I also had Karabiner-Elements running in the background to remap keys, which keeps the CAPS LOCK of multiple keyboards in sync, but you need to check a box for it to trigger the CAPS LOCK led. Ticking that made everything work as expected.
