### ISSUE TITLE
No RGB on 1% brightness

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wootility-issues#91]
**Description**
When the brightness is set to 1% all the LEDs are off, only at 2% or above they light on.

**Reproduction**
- none

**Media**
- none

**Systems**
 - Win 10

**Versions**
 - 3.6.14 Wootility
 - 1.30.12 firmware

**Products**
 - all

**Comment by Rocky04** [comment]
Was this addressed already? I'm not able to reproduce it with my Lekker keyboards.

**Comment by DarrenVs** [comment]
Looks to be resolved.
Can't reproduce it anymore either.
