### ISSUE TITLE
Feature: Allow mapping emojis to keys

### ISSUE THREAD

**Issue by szepeviktor** [WootingKb/wootility-issues#93]
**Describe the feature request**

Is it possible for a Wooting keyboard to type an emoji ❔ 
Or emojis could be only sent with a software?

**Comment by PastaJ36** [comment]
Would love this feature, but as far as I know this can only be done with software. The USB standard does not support UTF8 (codes that includes emoji) sadly

**Comment by Rocky04** [comment]
In the future when the Wooting may support macros it would be possible to send Alt codes to archive any character which is possible.

**Comment by szepeviktor** [comment]
> The USB standard does not support UTF8

I suspected that. The OS translates scan codes to characters.


There is "Sideband Input Device Protocol Spec"
https://deskthority.net/viewtopic.php?f=7&t=12927&start=

**Comment by ionstorm66** [comment]
Using the Hex Numpad/"alt code" with macros is pretty flaky. Better off using some software like WinCompose. 

This definitely shouldn't be a directly support item, macros will allow the user to pick.

**Comment by simon-wh** [comment]
I agree with the other comments here where this isn't necessarily something that should be directly supported and would be better as a side benefit of macro support

**Comment by szepeviktor** [comment]
Somehow this keyboard can type emojis: https://youtu.be/jyZM7IZhFS4?t=492

**Comment by ionstorm66** [comment]
> Somehow this keyboard can type emojis: https://youtu.be/jyZM7IZhFS4?t=492

Their firmware is opensource (which is really cool and nice :D) and they are just sending them as macros.
