### ISSUE TITLE
'Gamepad Mapping Override' does not reset keys if they were held down during profile switch

### ISSUE THREAD

**Issue by DarrenVs** [WootingKb/wootility-issues#95]
**Describe the bug**
When you switch to a profile with 'Gamepad Mapping Override' enabled, and hold down one of those keys, the key does not get reset and stays held down after switching.

**To Reproduce**
1. Create an analog profile with Gamepad Mapping Override enabled, and have analog bindings on a key(W) of the keyboard
2. Go to a text editor or website to test your keystrokes at
3. Switch to the Digital profile
4. Hold down one of the keys (W) that contains Analog bindings in the profile
5. While holding down the key (W), switch over to the Analog Profile containing the analog bind and Gamepad Mapping Override
6. Your key is now always pressed no matter the physical state of the key

**Wootility and Firmware version**
Firmware version: `1.30.12`
Wootility is version: `3.6.15`

**Comment by simon-wh** [comment]
Appears to resolved now in Wootility v4
